### ISSUE TITLE
Support Declarative Pipeline

### ISSUE THREAD

**Issue by batmat** [jenkinsci/JenkinsPipelineUnit#10]
Filing that around for feedback/ideas, even if I'm also looking into this a bit, though really not an experienced Groovy dev. Only using it casually. 

I think I should register the pipeline top function to `org.jenkinsci.plugins.pipeline.modeldefinition.model.Root` from `pipeline-model-definition`, but not sure what it would/could lead to yet.

**Comment by ozangunalp** [comment]
I guess the entry point is the `pipeline` step. Then there should be a parser which creates the pipeline model, that can be used as-is, and an interpreter to be mocked to create the imperative execution. 

I'll definitively look into it. Declarative pipelines are very useful to simplify pipeline code.

**Comment by macg33zr** [comment]
Hello -

If you want some ideas of what to add to support declarative pipelines, I have a github project using your framework to unit test with declarative pipeline. It is here: https://github.com/macg33zr/pipelineUnit
--Bill

**Comment by ozangunalp** [comment]
Hi Bill, 

I'd never tested it with Spock, seems great!
We work on the shared lib support right now. Next up is the support for declarative pipelines.
You give a great starting point there, I am planning to add more strict checking over the syntax of declarative pipelines.

**Comment by macg33zr** [comment]
Sounds great. I will keep an eye open for future updates. Thanks for your work on JenkinsPipelineUnit so far it really helped me!

**Comment by ozangunalp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Declarative Pipeline Support](https://trello.com/c/mMCSdvrs/1-declarative-pipeline-support)

**Comment by tarvitz** [comment]
Well, Already migrated my jenkins scripts to pipeline cause it gives better level of job control. Hope possibility to run test cases with it would emerge some day later ;)

**Comment by xbmono** [comment]
Can't wait to see this 👍

**Comment by dgoetsch** [comment]
You can get around this pretty easily...

in `setup()`

```    helper.registerAllowedMethod("pipeline", [Closure.class], { it -> it() })
```

**Comment by stchar** [comment]
#!13
