### ISSUE TITLE
How to test overriden steps?

### ISSUE THREAD

**Issue by nikola-da** [jenkinsci/JenkinsPipelineUnit#101]
There is a method to override builtin pipeline steps and from within them invoke the actual step (http://unethicalblogger.com/2017/08/03/overriding-builtin-steps-pipeline.html). It boils down to:

file: `vars/slackSend.groovy`
```
def call(Map args) {
  steps.slackSend args
}
```

However, I'm not sure how to test this, as I can't do `helper.registerAllowedMethod('slackSend', [Map.class], null)`, as it will skip the overriding implementation. Without registering method, JPU complains with:
```
Exception: groovy.lang.MissingPropertyException: No such property: steps for class: slackSend
```

If I add `binding.setProperty('steps', 'some')`, then JPU complains with:
```
Exception: groovy.lang.MissingMethodException: No signature of method: java.lang.String.slackSend() is applicable for argument types: (java.util.LinkedHashMap) values: [[message:Maybe]]
```

Pipeline code is:
```
@Library('jenkins-build-helpers@master') _
pipeline {
    stages {
        stage('One') {
            slackSend message: 'Maybe'
        }
    }
}
```

Test is:
```
    @Before
    void setUp() throws Exception {
        scriptRoots += 'test/jenkins'
        helper.registerSharedLibrary(library("jenkins-build-helpers")
                                     .defaultVersion('master')
                                     .targetPath('target')
                                     .retriever(LocalSource.localSource('target'))
                                     .build())
        super.setUp()
        binding.setProperty('steps', 'some')
    }

    @Test
    void shouldReturnTrueInProduction() {
        runScript(testScript)
    }
```

**Comment by stchar** [comment]
@nikola-da,

1st things first:

super.setUp() should be called before any manipulation with `helper` object

See https://github.com/jenkinsci/JenkinsPipelineUnit/pull/81

**Comment by stchar** [comment]
@DACH-NY,

Second concern is what's `steps` is it reference to pipeline methods in the shared library? Section Accessing steps
from https://jenkins.io/doc/book/pipeline/shared-libraries/

**Comment by stchar** [comment]
Closing the issue. Please reopen if you still need any help.
