### ISSUE TITLE
Testing with actual steps

### ISSUE THREAD

**Issue by jimklo** [jenkinsci/JenkinsPipelineUnit#102]
I'm trying to build a library that does some manipulation with git using the `sh` step.

Is there a way to use the actually `sh` step instead of having to write a mock that emulates `sh` step as the whole point of testing my library is to see if the specific things I'm doing (changing a file, adding the changes, committing locally) is actually working... mocking sh, just lets me see inspect the parameters passed to sh, doesn't guarantee that the sequence of commands I executed produce the correct result. 

To a certain extent this is true for any of the steps... I'm just looking for guidance on how to approach.

**Comment by mkobit** [comment]
FWIW, I wrote https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin to help with this kind of testing by using the `JenkinsRule` testing infrastructure.

**Comment by stchar** [comment]
Necroposting =)
Please take a look at https://github.com/jenkinsci/jenkinsfile-runner

**Comment by stchar** [comment]
I believe adding links to docs would be fine 
closing in in a favor of  #31
