### ISSUE TITLE
Unable to access default steps in global variables.

### ISSUE THREAD

**Issue by madelaney** [jenkinsci/JenkinsPipelineUnit#105]
I have a global variable (i.e. `vars/helloWorld.groovy`) with a signature of `def call(String message, Closure body`), when I try to test this global variable it (`vars/helloWorld.groovy`) fails saying that there is no such method `echo` or `sh`, which according to [Defining global variables
](https://jenkins.io/doc/book/pipeline/shared-libraries/#defining-global-variables) they should be able to access default steps (`sh`, `echo` ... etc) by default.

```java
def call(String message, Closure body = null) {
  echo "[INFO]: ${message}"
}
```

**Comment by stchar** [comment]
I think it is not a bug as there is a test to validate such a case:
 https://github.com/jenkinsci/JenkinsPipelineUnit/blob/912fb118a1cd27feb59d7e12feee40888f7c1006/src/test/groovy/com/lesfurets/jenkins/TestSharedLibraryWithLocalSourceRetriever.groovy#L47
