### ISSUE TITLE
Not sure I get it....

### ISSUE THREAD

**Issue by jonbuck16** [jenkinsci/JenkinsPipelineUnit#112]
So in regards to the regression testing functionality, is the point of this purely to pick up where something may have been accidentally changed that you wern't expecting and to hightlight it?  if not what **is** the point as if you change a pipeline then it will never match the previous recording so would always need to be updated and thus is not really highlighting or finding a regression bugs?

Secondly, how do you handle a use case where something is always different in a run without a pipeline being changed, for example I have some code that generates a timestamp which always produces a different value on every run without the pipeline changing therefore each run will never produce the same output as the previous run and thus will never match a recording!  How would you handle this situation?

Thanks
Jon

**Comment by stchar** [comment]
Hi, not sure how to help with `BaseRegressionTest` as haven't used this feature. 
But I can help you with mocking of modules with "randomized" output. 
Please reopen If it still actual.
