### ISSUE TITLE
Mocking closure declared in library

### ISSUE THREAD

**Issue by jfroche** [jenkinsci/JenkinsPipelineUnit#114]
Hello,
We are starting to use JenkinsPipelineUnit. We are stuck with the following groovy problem:

we have a library in src/be/company/Generic.groovy which does the following:
```groovy
package be.company;
def time(Closure cls) {
  timestamps {
    // do things before
    cls.call()
    // do things after
  }
}
```
`timestamps` is coming from this plugin: https://plugins.jenkins.io/timestamper
We are trying to mock the `timestamps` call using helper in our test like this:

```groovy
  @Override
  @Before
  void setUp() throws Exception {
      super.setUp()
      def library = library().name('jenkins-commons')
                       .defaultVersion("master")
                       .allowOverride(true)
                       .implicit(true)
                       .targetPath('build/libs')
                       .retriever(localSource('build/libs'))
                       .build()
      helper.registerSharedLibrary(library)
      helper.registerAllowedMethod("timestamps", [Closure.class], null)
  }
```
But this mock doesn't seem to have the correct signature as we receive this error:

```
groovy.lang.MissingMethodException: No signature of method: be.company.Generic.timestamps() is applicable for argument types: (be.company.Generic$_time_closure1) values: [be.company.Generic$_time_closure1@3058b282]
```

What would be the best way to declare the correct signature to this mock ?

Using Gradle 4.8 - Groovy 2.4.12 - JenkinsPipelineUnit 1.1

**Comment by cnserd** [comment]
I have this same exact problem and I read some other issues with the same content. It would be super nice if we can get an answer 🤞

**Comment by stchar** [comment]
You library class constructor should accept reference to the pipeline script. 

Please see !88

**Comment by williambrode** [comment]
@stchar is right.  Its worth noting that your code won't work when your run your pipeline too so it doesn't have to do with JenkinsPipelineUnit.  Another method of solving the problem is using groovy's closure delegate (what class to use to resolve the closure).  So you pass in the script and set the closure to use that as the delegate.

def time(Closure cls, Object script) {
  def closure = {
  timestamps {
    // do things before
    cls.call()
    // do things after
  }
}
 closure.delegate = script
 closure()
}

**Comment by luispollo** [comment]
@jfroche This might help you: https://github.com/jenkinsci/JenkinsPipelineUnit/issues/51#issuecomment-443361269 and https://github.com/jenkinsci/JenkinsPipelineUnit/issues/25#issuecomment-297575141

**Comment by jacob-keller** [comment]
I got this to work by setting the timestamps interceptor method to be a closure which takes the closure as an argument, and does cls.call() on it. (Since timestamps is a step which takes a closure).

Then, stuff inside the timestamps block gets called properly.

**Comment by BernalCarlos** [comment]
@luispollo Removing the "vars" directory for the "srcDir", does work, but it breaks IntelliJ autocompletion for code inside the vars directory, do you know what else can be done?

**Comment by stchar** [comment]
As wrote @jacob-keller the solution is:
```groovy
helper.registerAllowedMethod("timestamps", [Closure])
```
