### ISSUE TITLE
JenkinsPipelineUnit Roadmap

### ISSUE THREAD

**Issue by benemon** [jenkinsci/JenkinsPipelineUnit#124]
To formalise the output of a discussion with Pull Request #13 ...

It would be great to get a roadmap or at least a tentative understanding of timelines and objectives around this project and how the maintainer(s) see it developing in the future. The primary objective of this is to give future adopters confidence that this project is maintained, and how they can move forward with it.

**Comment by ozangunalp** [comment]
I totally support the initiative. Just want to note two things : 
- JPU doesn't exist in a vacuum. There are already lots of improvements we can do with building on the PRs already suggested. But in the long term this is something to sort out with the Jenkins core. 
- I'd be more than happy with coming up with a roadmap but timeline is not the word we are looking for, it implies commitment for new features etc., for which, as much as I enjoy contributing to the OSS, wouldn't sign up for. 

@benemon thanks for bootstrapping the initiative.

**Comment by ericis** [comment]
@ozangunalp Is anyone working to merge or close pull requests? I see ones that are 1+ years old and you are really the only contributor. We can't get a community behind this without moving PRs along...

**Comment by ericis** [comment]
Related: #122 #115

**Comment by stchar** [comment]
Hi, I suppose I'm a new maintainer. =) 

If you have any request what should be merged at first, please let me know.

**Comment by batmat** [comment]
@ericis I am not sure what you mean in your comment above at https://github.com/jenkinsci/JenkinsPipelineUnit/issues/124#issuecomment-438439620?

Are you proposing your help to review existing PRs? Would you like to also become a maintainer?
Thanks

**Comment by stchar** [comment]
It is possible to send a request to adopt this project 
https://jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/
