### ISSUE TITLE
How to mock httpRequest twice or more times?

### ISSUE THREAD

**Issue by anikitchuk** [jenkinsci/JenkinsPipelineUnit#125]
Hi, in my jenkins pipeline I have several stages with httpRequest plugin, I need to mock it several times to write a success test for all the pipeline:

`helper.registerAllowedMethod('httpRequest', [Map], { return ["status": 200, "content": "${response}"] })`

What is the proper way to mock plugins behavior when you use it more than ones in a pipeline?

**Comment by idij** [comment]
I don't know what's the proper way, but this is what I do. I'm using Spock.

in my base class:
```
    def registerMockMethod (name, signature) {
        def closure = Mock (name:name, Closure)
        helper.registerAllowedMethod (name, signature, closure)
        return closure
    }
```

Since it's a real mock you can set it up to behave as you wish for any given test.

e.g. in a test:

```
given: "a mock httpRequest"
    def httpRequest = registerMockMethod('httpRequest', [Map.class])

when: "I call a step that uses httpRequest"
    mypipeline.somemethod ()

then: "httpRequest is called once"
    1 * httpRequest (_) >> {  ["status": 200, "content": "${response}"]  }

```
You can replace the wildcard with a suitable matcher.  
Also, with spock, the wildcard param is available as `it[0][0]` inside the closure. e.g. `it[0][0].requestBody`

**Comment by dengayevskiy** [comment]
@idij Thanks for your answer. But the question is how to mock more than one httpRequests with different body for example. Like this: 

`helper.registerAllowedMethod('httpRequest', [Map], { return ["status": 200, "content": "${first_response}"] })`
`helper.registerAllowedMethod('httpRequest', [Map], { return ["status": 200, "content": "${second_response}"] })
`

**Comment by idij** [comment]
@dengayevskiy Once you have a real mock, you just put the expectations in sequence in the test.
    1 * httpRequest (_) >> {  ["status": 200, "content": "${first_response}"]  }
    1 * httpRequest (_) >> {  ["status": 200, "content": "${second_response}"]  }

**Comment by dengayevskiy** [comment]
You are talking about expectations but how can I tell jenkins-pipeline-unit to send me different responses for the method with one name ->  httpRequest?

**Comment by idij** [comment]
The expectations above cause the mock to return different responses for first and second calls to httpRequest. That's what you want, right?

As far as I can tell jenkinsPipelineUnit only supports a single handler for a method registered with register**Allowed**Method. i.e. unless you use a mocking framework, then "you can't" or "do it by implementing custom logic in your handler", etc.

OR, you register a real mock as your handler, like I did above. I introduced a register**Mock**Method in my base class, that lets you use a real mock that can have different expectations providing different responses, etc.

**Comment by anikitchuk** [comment]
@idij thanks for you answer, found the easiest way to do that without additional libraries

```
helper.registerAllowedMethod('httpRequest', [Map], { map ->
            if (map.url == "http://teamcity/app/rest/buildQueue") {
                return ["status": 200, "content": "${teamcity_trigger_response}"]
            } else if (map.url == "http://teamcity/app/rest/builds/id:${build_id}") {
                return ["status": 200, "content": "${teamcity_failed_response}"]
            } else if (map.url == "http://stash/rest/api/1.0/projects/SA/repos/repo/pull-requests") {
                return ["status": 200, "content": "${response}"]
            } else if (map.url == "http://stash/rest/api/1.0/projects/SA/repos/repo/pull-requests/${pull_request_id}/comments") {
                return ["status": 201]
            }
        })
```
