### ISSUE TITLE
MissingMethodException: No signature of method: GitflowMavenHelper.error() is applicable for argument types: (java.lang.String) values: [Stop the pipeline.]

### ISSUE THREAD

**Issue by jzy3d** [jenkinsci/JenkinsPipelineUnit#126]
Hi,

First, thanks for this great library!

I am trying to write a test in which I can mock [error()](https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#error-error-signal), a function available in Jenkins pipelines. 

Despite [BasePipelineTest already mocks the error function](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L76) my test is failing as follow

> MissingMethodException: No signature of method: GitflowMavenHelper.error() is applicable for argument types: (java.lang.String) values: [Stop the pipeline.]

My own test is already inheriting from this BasePipelineTest and setting up the test properly

```groovy
class GitflowMavenHelperTest extends BasePipelineTest {
    String TICKET = "CLOUD-4321"
    String CURRENT_VERSION_NO_SNAPSHOT = "6.7.8"
    String CURRENT_VERSION_SNAPSHOT = "6.7.8-CLOUD-4321-SNAPSHOT"

    @Override
    @Before
    void setUp() throws Exception {
        helper.baseScriptRoot = 'test/examples'

        super.setUp() // enable multiple mocks

        mockReadMavenPom(helper, "artifact", CURRENT_VERSION_NO_SNAPSHOT)
        mockUpdateGitlabCommitStatus(helper)
        mockGitlabCommitStatus(helper)
        mockWithMaven(helper)
        //mockError(helper)
    }
...
}
```

I tried adding my own mock to catch the call to error() as follow but it did not help

```groovy
 static void mockError(PipelineTestHelper helper){
    helper.registerAllowedMethod("error", [String.class], null)
 }

```

It seems I could replace `error("Stop the pipeline")` by `throw new Exception("Stop the pipeline")` to avoid mocking. But in that case I have to add lot of `try/catch` in my test cases and I do not like it a lot.

Does someone has a suggestion?

**Comment by luispollo** [comment]
I have the exact same problem. In my case the missing method was `echo()` (which is also mocked by the default helper), but I'm pretty sure it will happen with any method. Interestingly, when I call the same method directly from within the pipeline job script, it works, but when called from within a shared function I defined in `vars`, it doesn't, which suggests those mocks are not getting injected into the loaded scripts.

This works:
```groovy
def execute() {
    echo "test"
}
return this
```

This doesn't:
```groovy
sayHello()
return this
```
Where `sayHello` is defined in `vars/sayHello.groovy` as:
```groovy
def call() {
  println "Hello!"
}
```

Any ideas?

**Comment by luispollo** [comment]
@jzy3d This might help you: https://github.com/jenkinsci/JenkinsPipelineUnit/issues/51#issuecomment-443361269 and https://github.com/jenkinsci/JenkinsPipelineUnit/issues/25#issuecomment-297575141
