### ISSUE TITLE
vars not being set

### ISSUE THREAD

**Issue by doncorsean** [jenkinsci/JenkinsPipelineUnit#127]
I have a file in vars/foo.groovy
When I run the unit test I get groovy.lang.MissingPropertyException: No such property: foo for class

Shouldn't anything in vars/ be set without mocking?

**Comment by digulla** [comment]
Yes and it works for me. Your problem must be how you set up your test.
Remember that vars/ only works for shared pipeline libraries. If you want the tests inside the library (like I do), you can use a custom `SourceRetriever` when you define the library:

```
package com.lesfurets.jenkins.unit.global.lib

import groovy.transform.CompileStatic
import groovy.transform.Immutable

@Immutable
@CompileStatic
class ThisProject implements SourceRetriever {

    @Override
    List<URL> retrieve(String repository, String branch, String targetPath) {
        def sourceDir = new File("")
        return [sourceDir.toURI().toURL()]
    }

    static ThisProject thisProject() {
        new ThisProject()
    }

    @Override
    String toString() {
        return "ThisProject{}"
    }
}
```

You can then define your library like so:

        def library = LibraryConfiguration.library()
            .name('FooLibrary')
            .retriever(ThisProject.thisProject())
            .targetPath('.')
            .defaultVersion('master')
            .allowOverride(true)
            .implicit(false)
            .build()
        helper.registerSharedLibrary(library)

**Comment by stchar** [comment]
I agree with @digulla it maybe a result of a wrong project structure or a wrong usage of `LibraryConfiguration` 

@doncorsean, 
I'm closing this one. If is this till actual, please reopen.
