### ISSUE TITLE
Q: testing shared library

### ISSUE THREAD

**Issue by Tobrek** [jenkinsci/JenkinsPipelineUnit#128]
Hello,

i started to test our shared library methods using this framework. Currently i'm struggling with the problem that the binding of 'env' variable is lost when an imported class method is called:
 groovy.lang.MissingPropertyException: No such property: env for class: com.company.jenkins.helper.Library2Helper

```
package com.company.jenkins.helper
import com.company.jenkins.helper2.*

String getEnvVar() {
  return env.ENV_VAR
}

void writeEnvVar() {
  Library2Helper library2Helper = new Library2Helper()
  println library2Helper.getEnv2Var()
}
```

```
package com.company.jenkins.helper2
import com.company.jenkins.helper.*
class Library2Helper implements Serializable {
  String getEnv2Var() {
    return env.ENV_VAR
  }
}
```

```
package test.company.jenkins

import org.junit.*
import com.lesfurets.jenkins.unit.*
import static groovy.test.GroovyAssert.*
import com.company.jenkins.*

class HelperTest extends BasePipelineTest {
    def helperTest

    @Before
    void setUp() {
        super.setUp()
        helperTest = loadScript("src/com/company/jenkins/helper/LibraryHelper.groovy")
        binding.setVariable('env', [ENV_VAR:"envValue"])
    }

    @Test
    void testWriteEnvVarBase() {
        assertEquals "result:", "envValue", helperTest.getEnvVar()
    }

    @Test
    void testWriteEnvVarTry1() {
        assertEquals "result:", "envValue", helperTest.writeEnvVar()
    }

    @Test
    void testWriteEnvVarTry2() {
        helper.registerAllowedMethod("getEnvVar()", [Object.class], { 'env2Value' })
        assertEquals "result:", "env2Value", helperTest.writeEnvVar()
    }
}
```

- testWriteEnvVarBase works as expected - the `env`variable is used in the loaded class directly
- testWriteEnvVarTry1 - `env` is lost in the imported class
- testWriteEnvVarTry2 

My qestions:
a) Is this framework the wrong approach for testing the shared library methods?
b) What can i do to fix my `env`Problem? Any ideas?
c) If I understand idij's solution in #50, it is possible to register a shared library method for mocking, or not?

Thanks for your time and help.

**Comment by Tobrek** [comment]
found a solution => closed

**Comment by MorganGeek** [comment]
@Tobrek Hi, could you please share your solution ? 😄 Thanks !

**Comment by Tobrek** [comment]
Hello MorganGeek,

we decided that
a) this is the wrong framework for our intention to test the library methods in src (and vars). Maybe we will give it a new try, when we will start testing at Jenkinsfile level. For testing the library methods we are using standard groovy unit tests.
b) env variables are available in the Jenkins environment, but not in groovy unit tests. (Maybe there is a way to create a workaround or something else, like manually creating the env property map, but i give up to search for.)
I created a helper class to access the env variables directly, without any other logic. Thats a bit creepy and circuitous, but now accessing the env variables is mockable at a central point. 
c) mocking library and Jenkins plugin methods is possible by using the groovy MetaClass.

Regards
Daniel

**Comment by MorganGeek** [comment]
Thanks @Tobrek for taking the time to share your view :) , I'm also in research mode for unit testing our pipeline library ;) , and I do agree it's not that easy.

**Comment by mcascone** [comment]
> b) Env variables are available in the Jenkins environment, but not in groovy unit tests. (Maybe there is a way to create a workaround or something else, like manually creating the env property map, but i gave up to search for.) I created a helper class to access the env variables directly, without any other logic. Thats a bit creepy and circuitous, but now accessing the env variables is mockable at a central point. 
> Regards Daniel

Hi, you should be able to use the env var binding:
```
binding.setVariable('env', [varname1: 'value1', varname2: 'value2', ...]
```

The same works for `params`. I don't remember where i found that, but it works pretty well. I think there are also `getVariable`, `addVariable`, etc to make it a bit less kludgy to modify them on the fly.
