### ISSUE TITLE
Jenkins Pipeline Unit doesn't discover pipeline step dependencies in vars

### ISSUE THREAD

**Issue by veganafro** [jenkinsci/JenkinsPipelineUnit#132]
The issue I'm experiencing is as follows: when testing step A in my Jenkins pipeline that leverages step B, step B is searched for as if it were a member method of step A, with this error message being displayed

`groovy.lang.MissingMethodException: No signature of method: callHello.hello() is applicable for argument types: () values: []`

I've tried explicitly importing step B in step A (both static import and not) with limited success. Non-statically importing step B, constructing an instance of it, then finally calling that instance of step B in step A works. However, if step B includes a Jenkins DSL construct like `dir` or `sh`, the same issue occurs where `sh` is searched for as if it were a member of step B. Thanks in advance.

For context, here is my project structure:
```
dummy-project
 └── vars
 │     ├── hello.groovy
 │     └── callHello.groovy
 └── test
 │     └── TestCallHello.groovy
 ├── build.gradle
 └── Dockerfile
```

The contents of `build.gradle`:
```
apply plugin: 'groovy'

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.4.15'

    testCompile 'junit:junit:4.12'
    testCompile group:'com.lesfurets', name:'jenkins-pipeline-unit', version:'1.0'
    testCompile group:'org.assertj',   name:'assertj-core', version:'3.4.1'
    testCompile 'org.mockito:mockito-inline:+'
}

sourceSets {
    test {
        groovy {
            srcDirs = ['vars', 'test']
        }
    }
}
```

The simple test:
```
import org.junit.Test
import org.junit.Before
import com.lesfurets.jenkins.unit.BasePipelineTest

class TestCallHello extends BasePipelineTest {

      @Override
      @Before
      void setUp() throws Exception {
          super.setUp()
      }

      @Test public void callHelloTest() throws Exception {
          def script = loadScript('vars/callHello.groovy')
          script.invokeMethod('call')
          printCallStack()
      }
}
```

And finally, the contents of my pipeline steps:
```
// callHello.groovy

def call() {
    hello()
}

return this

// hello.groovy

def call() {
    sh 'echo hello'
    return 'hello world'
}

return this
```

**Comment by stchar** [comment]
@veganafro, hi I think you're trying to test a shared library. 
but the way you work with `vars` is not like described in the [doc](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/README.md#testing-shared-libraries )

**Comment by stchar** [comment]
When you call
```
def script = loadScript('vars/callHello.groovy')
```
`helper` loads the exactly groovy script using `GroovyScriptEngine` it has no clue about other scripts in your `vars` folder until you load them explicitly, but I don't think It would make any their methods globally accessible but "global" variables as it uses same `biniding` object.

I think it is working as designed. Closing the issue.
