### ISSUE TITLE
Execution is very slow with many unit tests

### ISSUE THREAD

**Issue by dgoetsch** [jenkinsci/JenkinsPipelineUnit#134]
When using this library, execution according to examples is very slow.  Essentially, initialization of `BasePipelineTest` and loading/compiling the Jenkinsfile together take multiple seconds.

Running `super.setup()` and loading the Jenkinsfile ONCE for all tests in a class drastically speeds up test execution.   I've implemented this by adding a JUnit Runner that runs all tests in a class against a  single instance of BasePipelineTest. (each test takes 10ms vs 2+ seconds)

I propose this project integrates a similar JUnit Runner.

**Comment by stchar** [comment]
@dgoetsch 
#74 register helper as singleton, can you try it? Maybe it will help you.

New version 1.2 available in http://repo.jenkins-ci.org/releases
http://repo.jenkins-ci.org/releases/com/lesfurets/jenkins-pipeline-unit/1.2

**Comment by stchar** [comment]
Closing as there is no feedback.
