### ISSUE TITLE
When should I use BasePipelineTest vs BasePipelineTestCPS?

### ISSUE THREAD

**Issue by jordanjennings** [jenkinsci/JenkinsPipelineUnit#137]
When should I use `BasePipelineTest` and when should I use `BasePipelineTestCPS`?

I am aware that Jenkins transforms Groovy scripts to CPS, so I would assume I'd always want to use something that more closely resembles the CPS transformation that Jenkins does. I did some quick testing and I can't see any difference functionally in my tests whether I extend one or the other, even if I use non-CPS friendly code.

**Comment by stchar** [comment]
@jordanjennings, this is a good question

AFAIK The purpose of `BasePipelineTestCPS` is to verify serialization issues. 
According to sources `BasePipelineTestCPS` considering to use own test helper  `PipelineTestHelperCPS` which process pipeline scrips as `CPS`. 
The framework also tries to fake the way how pipeline executes `CPS Closure`

Personally i'm not using this feature, so i'm not the best guy to follow.

**Comment by digulla** [comment]
I'm using both. Since the CPS code makes the tests very slow, I have two test classes which share the same setup. 
When I write new code and want to check for CPS bugs, I add a new test case in the CPS test class.
When the code works, I move the test to the non-CPS test class.
