### ISSUE TITLE
Add support for withMaven()

### ISSUE THREAD

**Issue by digulla** [jenkinsci/JenkinsPipelineUnit#140]
Please add a default implementation for `withMaven()` so people have an idea how to that.
Here is my version as a reference:

        helper.registerAllowedMethod('withMaven', [Map.class, Closure.class]) { options, c ->
            c.delegate = delegate
            helper.callClosure(c)
        }

**Comment by stchar** [comment]
@digulla 
That's great idea, PR is welcome =)

**Comment by digulla** [comment]
Is my code correct?

**Comment by stchar** [comment]
@digulla, yep looks good

**Comment by digulla** [comment]
I created a PR but it's for my fork and not the main project.
Please copy the code into your project and close this issue, I don't have time to figure out how to do this.

**Comment by nre-ableton** [comment]
@digulla Please resubmit a PR to this project, or close this issue if you are no longer interested in having this function in the main project.

**Comment by digulla** [comment]
How do I "resubmit a PR to this project"? I see no buttons or tools to do that.

**Comment by nre-ableton** [comment]
Sorry, I was not specific enough. You need to:

1. Close https://github.com/digulla/JenkinsPipelineUnit/pull/1, as it is pointing to the wrong repository
2. [Open a new PR](https://github.com/jenkinsci/JenkinsPipelineUnit/compare/master...digulla:digulla-patch-140) in your repository, but make sure that the base repository is the upstream one. It should look like this:

![Screenshot from 2021-11-12 11-28-38](https://user-images.githubusercontent.com/16208985/141452367-957b8a8a-77e1-4984-838a-be1586d21792.png)

**Comment by digulla** [comment]
I just have 300K on StackOverflow, I'm too stupid to use GitHub...

**Comment by nre-ableton** [comment]
@digulla Intelligence and experience are two different things. :smile: Anyways, the new PR looks correct, thanks for taking the time to fix it.
