### ISSUE TITLE
the default mock of error step is incorrect

### ISSUE THREAD

**Issue by addozhang** [jenkinsci/JenkinsPipelineUnit#143]
The correct logic of `error` step is marking status `FAILURE` and fast-fail.

But the default mocking logic in `BasePipelineTest` is below. It is just update build status to `FAILURE`.  So the running keeps going after error step.

```groovy
helper.registerAllowedMethod("error", [String.class], { updateBuildStatus('FAILURE') })
```

**Comment by stchar** [comment]
This need rework for a case when error is produced in a branch of `parallel` and `failfast` is set to false.

So far you can workaround this overriding `error` method in you `.*Test`classes. 
If you need to verify exactly error in your test please follow the docs
(see #94)
