### ISSUE TITLE
Traditional Class/Method Testing with Script Calls

### ISSUE THREAD

**Issue by jenrsparks** [jenkinsci/JenkinsPipelineUnit#151]
I'm working on a team's project which has a **lot** of different Util classes, and they're all created in the same way - a Groovy class, following traditional OO paradigms, as such:

```
package com.company.utils

class StringUtils {

   def steps

   StringUtils(steps) {
      this.steps = steps
   }

   def getString(def obj) {
      steps.echo "Converting object to string version: ${obj.toString()}"
      return obj.toString()
   }

}
```
(It's not this simplistic, but hopefully that conveys my intent.)

I've been able to use JenkinsPipelineUnit for testing a Jenkinsfile format, and even a declarative one with some creative helper registrations. And, perhaps obviously, the pure Groovy classes can be tested with something like JUnit/Mockito/etc.

But what's not clear to me is if I can use JenkinsPipelineUnit to exercise the aforementioned paradigm of passing the script into the class on construction, and using it to make DSL calls. The closest I could find was the example in `TestUtilsLib.groovy`, however this would mean convincing this team to convert the *entirety* of their Utils into a different paradigm.

Apologies if this is an obvious question - still wrapping my arms around JenkinsPipelineUnit. If anyone has any clever suggestions, I'd appreciate hearing them! Thanks so much!

**Comment by idij** [comment]
This is how I do it. Not sure it's the right way, but works for what I need, and seems similar to your problem:

I have two files, one for the test (MyClassTest.groovy), and one to create a jenkins pipeline script that acts as a factory for the class (MyClassTest.jenkins). 

```
@Library ('MyLibrary') _
def call (step) {
    return new MyClass (this)
}
return this
```

The test does a `loadScript` to get the factory, and uses the factory to create an object instance:

```
def myClassFactory = loadScript ("path/to/MyClassTest.jenkins")
def myClassObjectInstance = myClassFactory ()
```

The MyClass can use the parameter to echo or whatever.

```
MyClass (context) {
    context.echo "hello"
}
```

**Comment by jenrsparks** [comment]
@idij - Interesting approach! For whatever reason, the `context` is coming back null.

I've got the following utility class:

```
class DummyUtil {
    def steps
    DummyUtil(steps) {
        this.steps = steps
    }

    void doSomeSteps() {
        steps.withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: "${steps.env.credentials}", usernameVariable: 'username', passwordVariable: 'pw']]) {
            echo "Something witty."
        }
    }
}
```

Then the DummyUtilTest.jenkins:
```
def call(steps) {
  return new DummyUtil(steps)
}
```

And our test:

```
class DummyUtilTest extends BasePipelineTest {
    [excluding binding & helper setup]

    @Test
    void doSomeSteps() {
        def utilFactory = loadScript("path/to/test/package/DummyUtilTest.jenkins")
        DummyUtil util = utilFactory()

        util.doSomeSteps()
    }
}
```

I'm getting a NullPointerException, and it's around the `steps` being passed around. Thoughts on why this might be happening and how to resolve it?

**Comment by jenrsparks** [comment]
@idij I think I figured it out!

Instead of calling `return new DummyUtil(steps)`, I needed `return new DummyUtil(this)` - which caused everything to be able to work through calls to `steps` and handle the appropriate mocking being done with the helper & binding calls.

Thanks so much for helping get this on the right path!
