### ISSUE TITLE
global environment variables not used

### ISSUE THREAD

**Issue by danhiris** [jenkinsci/JenkinsPipelineUnit#153]
I'm trying to test pipeline code for building some images.
When I run the test, it fails to use jenkins environment variables like the BRANCH_NAME of the branch I'm currently in with the following error:

> groovy.lang.MissingPropertyException: No such property: env for class: dockerBuild

Adding the following to the test doesn't work because that is not an actual variable name.

`binding.setVariable("env.BRANCH_NAME", "develop") `

**Comment by mat1e** [comment]
Hi, did you try with 
`binding.setVariable('env', [BRANCH_NAME: 'develop'])`

**Comment by tiger5226** [comment]
I am having the same issue. Unfortunately, that does working for me. I am testing some shared library code and it accesses the env object. I was setting the following:

`binding.setVariable('env',[JOB_NAME:'MyMockJobName'])`

I get the same error:

`groovy.lang.MissingPropertyException: No such property: env for class: main.groovy.org.utilities.Utils`

Maybe this only works from the global var being tested?

**Comment by philippart-s** [comment]
The vars are store in a map so you must use a map like this : 
```java
HashMap env = new HashMap();
env.put("BRANCH_NAME", "foo");
getBinding().setVariable("env", env);
```

**Comment by waytoharish** [comment]
> I am having the same issue. Unfortunately, that does not work for me. I am testing some shared library code and it accesses the env object. I was setting the following:
> 
> `binding.setVariable('env',[JOB_NAME:'MyMockJobName'])`
> 
> I get the same error:
> 
> ```
> groovy.lang.MissingPropertyException: No such property: env for class: main.groovy.org.utilities.Utils
> ```
> 
> Maybe this only works from the global var being tested?
> 
> I have also tried setting a property similarly since the error message mentions the word property.

is that work for you ??

**Comment by philippart-s** [comment]
Hi,

For the mock of env variable I use `setProperty` method not `setVariable` : 
`binding.setProperty("env", [BRANCH_NAME: 'branch/foo'])`.

I'm not grovvy expert so I'm can"t explain the difference between `setVariable` and `setProperty` in [Binding](https://docs.groovy-lang.org/latest/html/api/groovy/lang/Binding.html) class.

Hope that's solve your problem.
