### ISSUE TITLE
Is this project dead, or in need of adoption?

### ISSUE THREAD

**Issue by nre-ableton** [jenkinsci/JenkinsPipelineUnit#156]
There hasn't been much activity in this repo for 2 years. A bunch of pull requests have piled up, many of them quite trivial. Is this project in need of adoption? Ping @ozangunalp

**Comment by apgsga-jhe** [comment]
I have exactly the same concern, does this project still lives? It looks to be something very useful/promessing, but doe it have any future? Ping @ozangunalp as well ...

**Comment by nre-ableton** [comment]
FWIW, I would be happy to adopt this project. We are using this framework at my workplace, so I'm already maintaining it during working hours.

**Comment by ozangunalp** [comment]
Hey Nick, Julien, I'd be happy to have a chat in the [Gitter](https://gitter.im/JenkinsPipelineUnit/Lobby). Would you be available in the Sunday afternoon CET ? 

Nick, I've seen your [mocks repo](https://github.com/AbletonDevTools/jenkins-pipeline-mocks), seems really helpful, we should check to integrate it to the main project. We can discuss to have you as contributor/maintainer in the project.

Cheers and hope to discuss soon

**Comment by nre-ableton** [comment]
@ozangunalp Thanks for the reply! Sunday sounds good, I'm also in CET so just let me know a specific time and I'll be there.

**Comment by apgsga-jhe** [comment]
Unfortunately Sunday won't be possible for me.

**Comment by aksenov007** [comment]
What's the status? And, by the way, when will be upcoming release? There are 53 commits in master since the last release 2 years ago.

**Comment by nre-ableton** [comment]
@ozangunalp Sorry I missed you last time -- should we try to reschedule for another weekend?

**Comment by mccrackend** [comment]
Any update on this?  Would love to see the next release come out!

**Comment by marshallford** [comment]
Similarly to @mccrackend I'd like to see a release cut, specifically one that includes: PR #131.

**Comment by stchar** [comment]
Released 1.2. Now you can send adoption request to jenkinsci as they do for plugins.
see https://jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

**Comment by nre-ableton** [comment]
FYI @ozangunalp: I made a request to the Jenkins developers mailing list as recommended by @stchar in https://github.com/jenkinsci/JenkinsPipelineUnit/issues/156#issuecomment-561608219. I hope that you don't mind! 😄 I would appreciate committer rights to the project, and obviously my main intention is to help maintain the project, review PRs, improve test coverage, etc.

**Comment by ozangunalp** [comment]
@nre-ableton no problem for me! I very much appreciate that @stchar is taking over the maintainer role for the project.
