### ISSUE TITLE
How to mock artifactory dsl steps and methods 

### ISSUE THREAD

**Issue by manjeet88** [jenkinsci/JenkinsPipelineUnit#158]
How to mock the artifactory jenkins pipeline dsl steps and methods with this unit test framework ?

**Comment by stchar** [comment]
please use `helper.registerAllowedMethod`

**Comment by manjeet88** [comment]
I have a method like this 

void executeWithArtifactory(Map params = [:]) {
    def rtMaven = Artifactory.newMavenBuild()
    rtMaven.resolver(
        releaseRepo: artifactoryResolver,
        snapshotRepo: artifactoryResolver,
        server: params.artifactoryServer
    )
    rtMaven.deployer(
        releaseRepo: params.releaseDeploymentRepo,
        snapshotRepo: params.snapshotDeploymentRepo,
        server: params.artifactoryServer
    )

   def buildInfo = rtMaven.run(pom: pomPath, goals: mavenArgs)
   params.artifactoryServer.publishBuildInfo buildInfo
}

How can i mock Artifactory.newMavenBuild() ? It doen't work with helper.registerAllowedMethod ?

**Comment by stchar** [comment]
I may guess you're trying to test a shared library.
If you're assume `Artifactory` class  to be in the `class path` when test is runnig 
then you can a use solution to mock a static method
see https://dzone.com/articles/mocking-static-methods-groovy
