### ISSUE TITLE
How to generate code coverage using gradle task for these unit test cases?

### ISSUE THREAD

**Issue by manjeet88** [jenkinsci/JenkinsPipelineUnit#163]
Hi,

I am looking for a way to generate code coverage for unit test case for pipeline using gradle ?

**Comment by manjeet88** [comment]
@ozangunalp @stchar ?

**Comment by stchar** [comment]
I haven't used this feature so far,  as far as I know the feature is not yet implemented for shared libraries.
If I not mistaken it was discussed at https://github.com/jenkinsci/JenkinsPipelineUnit/issues/103

**Comment by stchar** [comment]
Closing in favor of #103. Please consider using gitter channel for questions.
