### ISSUE TITLE
loadScript not accepting argument

### ISSUE THREAD

**Issue by dtrogers2** [jenkinsci/JenkinsPipelineUnit#171]
I'm currently using Maven to build the project and execute groovy script using gmavenplus-plugin 1.8.1. The script is executed in the prepare-package phase.

Here's the groovy script that I'm executing that is calling loadScript():
`import com.lesfurets.jenkins.unit.BasePipelineTest
class TestCase extends BasePipelineTest {
	public static void main(String[] args){
		def script = loadScript('/hello.groovy')
		script.execute()
		printCallStack()
	}
}`

For some reason when I use either loadScript or runScript I get the following error:
>[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.8.1:execute (default-cli) on project test4: Error occurred while calling a method on a Groovy class from classpath. InvocationTargetException: groovy.lang.MissingMethodException: No signature of method: static TestCase.loadScript() is applicable for argument types: (java.lang.String) values: [/hello.groovy]

>[ERROR] Possible solutions: loadScript(java.lang.String), runScript(java.lang.String), runScript(groovy.lang.Script)

What could be causing this?

**Comment by stchar** [comment]
I'm not sure why do you need a main in testcase, haven't seen such a usage before.

Anyway, main is a static method.

From static method you can only call static methods, to call runScript you need to create an instance of TestCase class

**Comment by stchar** [comment]
Unfortunately there is no example how to run tests with maven but I think 
`gmaven-plugin` could fit the needs
* Example of `pom.xml`
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
		 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.hcm</groupId>
    <artifactId>jpu-example</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
    </properties>

    <repositories>
        <repository>
        <id>jenkins-ci-releases</id>
        <url>https://repo.jenkins-ci.org/releases/</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.lesfurets</groupId>
            <artifactId>jenkins-pipeline-unit</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.7</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.gmaven</groupId>
                <artifactId>gmaven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>generateStubs</goal>
                            <goal>compile</goal>
                            <goal>generateTestStubs</goal>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <providerSelection>2.0</providerSelection>
                    <source>2.0</source>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
