### ISSUE TITLE
Environment Variables Not Recognized in Agent section

### ISSUE THREAD

**Issue by dtrogers2** [jenkinsci/JenkinsPipelineUnit#180]
I'm using Maven to execute the groovy script that calls the JPU module.
In my setUp(), I use binding.setVariable to set the environment variable loadDirectory.
In the Jenkinsfiles that are currently being used by my company, the customWorkspace method is used with loadDirectory as the parameter inside the Agent Node section of the pipeline

Within the Stage Steps sections, the loadDirectory is able to be to be used. But when I attempt to set customWorkspace to the loadDirectory environment variable in the Agent Node section I receive the following error:
`[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.8.1:execute (default-cli) on project test4: Error occurred while calling a method on a Groovy class from classpath. InvocationTargetException: No such property: loadDirectory for class: com.lesfurets.jenkins.unit.declarative.AgentDeclaration -> [Help 1]`

I've attached the related files so you can see the code I'm using in more detail.
TestMain is originally TestMain.groovy, and testPipeline is originally testPipeline.Jenkinsfile, but those file types are not allowed to be uploaded to github.
[TestMain.txt](https://github.com/jenkinsci/JenkinsPipelineUnit/files/4283142/TestMain.txt)
[testPipeline .txt](https://github.com/jenkinsci/JenkinsPipelineUnit/files/4283147/testPipeline.txt)

**Comment by stchar** [comment]
Yep it's a bug.
thank you.
I believe workaround would be:

```groovy
def local = env. ENV_VAR
pipeline {
  agent { 
    label local
  }
...
}
```
