### ISSUE TITLE
exception in phase 'semantic analysis'

### ISSUE THREAD

**Issue by william76** [jenkinsci/JenkinsPipelineUnit#189]
I'm trying this out to see if it can be used to drive some unit testing on our pipelines.  

As best as I can tell, after cloning this, I should run the `gradlew` command... but I get an error with this:

```
$ gradlew
> Task :buildSrc:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileGroovy'.
> BUG! exception in phase 'semantic analysis' in source unit '<home>/tmp/JenkinsPipelineUnit/buildSrc/src/main/groovy/com/lesfurets/gradle/CopyDependenciesToMavenTreeTask.groovy' Unsupported class file major version 57

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

I'm running OSX 10.14.6 and have homebrew for package management.

**Comment by stchar** [comment]
what is the version of java you use?

Does it looks like this one? https://github.com/exercism/support/issues/73#issuecomment-538303598

**Comment by stchar** [comment]
@william76, could you please provide additional info( gradle, java, groovy version).

**Comment by stchar** [comment]
ping @william76

**Comment by stchar** [comment]
I'm closing as there is no feedback for a long time, hope you're doing well.
