### ISSUE TITLE
No signature of method ValidateWhitelistTest.callArgsToString() is applicable for argument types: (com.lesfurets.jenkins.unit.MethodCall) 

### ISSUE THREAD

**Issue by Suchismita1tutun** [jenkinsci/JenkinsPipelineUnit#203]
Getting missing method exception :
groovy.lang.MissingMethodException: No signature of method: ValidateWhitelistTest.callArgsToString() is applicable for argument types: (com.lesfurets.jenkins.unit.MethodCall) values: [      validateSample.error(.........)

Here is the output of printStackTrace()
```   
validateSample.call(textString)
      validateSample.libraryResource(sample.json)
      validateSample.error(Some error msg)

```

validateSample is the groovy file under var directory 
Any help would be appreciated. 

I am using version 1.3 of com.lesfurets:jenkins-pipeline-unit.

**Comment by stchar** [comment]
@Suchismita1tutun  `callArgsToString` I assume you're trying to validate call-stack 
https://github.com/jenkinsci/JenkinsPipelineUnit#analyze-the-mock-execution

Could you please share this part of your test. Whether the README example is incorrect or whether your's test contains an error.

I'm also using snippet like:
```
assertThat(helper.callStack.stream()
        .filter { c -> c.methodName ==~ /echo/  }
        .map(MethodCall.&callArgsToString)
        .findAll { s -> s =~ /Hello.*/ })
        .hasSize(1)
```
to validate line like : echo "Hello World"

**Comment by stchar** [comment]
I hope it helped. I'm closing this one. Please reopen if you still need an assist.

**Comment by kromg** [comment]
Hi, just for future reference, for those like me hitting this problem: ensure you've imported the method, like: 

`import static com.lesfurets.jenkins.unit.MethodCall.callArgsToString`
