### ISSUE TITLE
Provide a mechanism to stub agent methods in declarative pipelines

### ISSUE THREAD

**Issue by danielsiwiec** [jenkinsci/JenkinsPipelineUnit#208]
I have a pipeline that has this block:

```
stage('Unit') {
  agent {
    kubernetes {
      label 'jenkins-slave'
      defaultContainer 'docker-alpine'
    }
  }
  steps {
    sh 'make clean tests.unit'
  }
}
```

Currently, the test fails with an error regarding the missing method `kubernetes` on the Agent. It would be useful, to provide a way to stub these methods, similar to the existing `helper.registerAllowedMethod`

**Comment by stchar** [comment]
Thanks for the finding. 
This is similar to #180 
We need to refactor `agent` closure to use delegate of the `pipeline {}` which allows us to access to mocked Jenkins methods and global variables.
