### ISSUE TITLE
Need to manually add assertj-core to build.gradle dependencies

### ISSUE THREAD

**Issue by nre-ableton** [jenkinsci/JenkinsPipelineUnit#209]
I'm in the process of updating some of my projects from JenkinsPipelineUnit 1.0 to 1.4, and I now need to add the following to my `build.gradle` to make it work:

```gradle
dependencies {
  compile 'com.github.AbletonDevTools:jenkins-pipeline-mocks:0.8+'
  compile 'org.codehaus.groovy:groovy-all:2.4.12'

  testCompile 'org.assertj:assertj-core:3.15+' // <-- this
  testCompile 'junit:junit:4.13'
  testCompile(group: 'com.lesfurets', name: 'jenkins-pipeline-unit', version: '1.4')
}
```

If I omit the `testCompile 'org.assertj:assertj-core:3.15+'` line, I get this error when running `./gradlew test`:

> `Task :compileTestGroovy FAILED`
> `FAILURE: Build failed with an exception.`
> `* What went wrong:`
> `Execution failed for task ':compileTestGroovy'.`
> `Unable to load class com.lesfurets.jenkins.unit.BasePipelineTest due to missing dependency org/assertj/core/api/AbstractCharSequenceAssert`

I'm not terribly skilled with Gradle, but I had a look at this project's `build.gradle` file and everything seemed to be in order. Am I missing something obvious?

**Comment by TobiX** [comment]
Probably caused by #185, this wasn't the case with 1.3

**Comment by brianeray** [comment]
I just hit this error in a slightly different context, as we have another Spock-specific framework sitting on top of JPU:

`
  implementation 'com.lesfurets:jenkins-pipeline-unit:1.4'
`

So the exception is thrown earlier in this project, during `:compileGroovy`.

I believe there's some difference between `compile` and `implementation`, and `testCompile` and `testImplementation` as in the #185 refactor. We have other projects in which switching from the former to the latter also caused transitive dependencies falling off the classpath.

**Comment by brianeray** [comment]
The POMs in the 1.3 and 1.4 JARs show different dependency scopes.

```
@@ -78,5 +78,5 @@
       <artifactId>assertj-core</artifactId>
       <version>3.4.1</version>
-      <scope>compile</scope>
+      <scope>runtime</scope>
     </dependency>
```

That might be a downstream side effect of Gradle's deprecation of `compile` and `testCompile`.

**Comment by nre-ableton** [comment]
@brianeray That does indeed look like the cause of this change. The question is, how should we fix this? I think that reverting to `compile` is probably unwise, given that it is deprecated. However, I noticed that assert4j is included twice in the `dependencies` section. Would removing the second `testImplementation` dependency for assertj4 fix this?

Also, n00b Gradle question, but what target can I run to generate the `pom.xml` file, as you did above?

**Comment by TobiX** [comment]
@nre-ableton You can run
```
gradlew tasks
```
to get an overview of what is available. Skimming the list, I found
```
gradlew generatePomFileForMavenPublication
```
which seems to be documented here: https://docs.gradle.org/current/userguide/publishing_maven.html

...

**Comment by brianeray** [comment]
And the POM is also generated implicitly with the `publish` task, I'm pretty sure.

I agree that reverting to `compile` (and `test`) is probably a bad idea.

I don't think that removing the `testImplementation` dependency would fix it but it would be a relatively easy experiment to try. My guess is that the JPU unit tests would likely either fail to compile or fail to run.

I will dig deeper. Gradle has such sophisticated dependency resolution functionality there may be an even simpler way to tell it to treat at least `assertj-core` referenced in the JPU POM as a transitive dependency that should be put on the classpath.

**Comment by TobiX** [comment]
The guide (https://docs.gradle.org/current/userguide/publishing_setup.html) suggest using `java-library` instead of `java` - If nobody else volunteers, I'll try to provide a pull request later :D

**Comment by brianeray** [comment]
@TobiX you beat me to it. The current project should be using this plugijn and `api` dependencies instead of `implementation`, it seems. When I make changes to the v1.4 `build.gradle` thus,

```
diff --git a/build.gradle b/build.gradle
index baaadf9..754c04b 100644
--- a/build.gradle
+++ b/build.gradle
@@ -4,7 +4,7 @@ plugins {
     id "com.jfrog.artifactory" version "4.11.0"
     id 'groovy'
     id 'maven-publish'
-    id 'java'
+    id 'java-library'
     id 'jacoco'
     id 'net.researchgate.release' version '2.8.1'
 }
@@ -36,10 +36,9 @@ dependencies {
     implementation('com.cloudbees:groovy-cps:1.12')
     implementation('commons-io:commons-io:2.5')
     implementation('org.apache.ivy:ivy:2.4.0')
-    implementation('org.assertj:assertj-core:3.4.1')
+    api('org.assertj:assertj-core:3.4.1')
     implementation('org.apache.commons:commons-lang3:3.5')

-    testImplementation('org.assertj:assertj-core:3.4.1')
     testImplementation('junit:junit:4.11')
```

This yields in `pom.xml` this:

```
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.4.1</version>
      <scope>compile</scope>
    </dependency>
```

And the [Java Library doc](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph) suggests it might be safe to eliminate the `testImplementation` dependency in that case.

**Comment by brianeray** [comment]
... Unit tests do pass.

```
> gradle --warning-mode=all --console=rich test

> Task :copyGrapesDependencies
Property 'configuration' has @Input annotation used on property of type 'Configuration'. This behaviour has been deprecated
 and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.4/userguide/more_about_tasks.html#sec:up_to_da
te_checks for more details.

> Task :test

com.lesfurets.jenkins.TestPipelineJava > should_return_cleanname PASSED

com.lesfurets.jenkins.TestCustomMethodJob > should_run_script_with_custom_method_with_arguments_mock PASSED

 [...]

com.lesfurets.jenkins.unit.PipelineTestHelperTest > testRegisterAllowedMethodWithoutArgs PASSED

com.lesfurets.jenkins.unit.PipelineTestHelperTest > testRegisterAllowedMethodEmptyArgs PASSED

BUILD SUCCESSFUL in 30s
6 actionable tasks: 6 executed
```

@TobiX I'm happy to submit a PR too, after some more testing with our projects that depend on it. Let me know.

This leads me to wonder if any of the other `implementation` dependencies should switch to `api`. Maybe that will come out in testing.

**Comment by TobiX** [comment]
@brianeray Sure, go ahead.

Does your build run with Gradle 6? Probably a good idea for a pull request to update the gradle wrapper, too :D

**Comment by brianeray** [comment]
Aha yes, that warning gave it away. Trying to stay current because Gradle moves so fast.

That's a good idea. But first, on to the current fix. PR hopefully by end of day tomorrow owing to other tasks. (Relatedly I'm in UTC -7; my end of day is probably later than that of others here.)

**Comment by stchar** [comment]
@nre-ableton 
I've also did a migration of my projects, but some of my test are using 
```
import static org.assertj.core.api.Assertions.assertThat
```
Which is a part of `org.assertj:assertj-core:...`, so I have never came across with you issue.

**Comment by brianeray** [comment]
Unfortunately due to those other tasks I hinted at, optimistically it's looking more like end of day Friday for my PR. But more likely next Monday.

**Comment by brianeray** [comment]
#215

**Comment by nre-ableton** [comment]
Fixed by https://github.com/jenkinsci/JenkinsPipelineUnit/pull/215, thanks @brianeray
