### ISSUE TITLE
Mixing Optional and Required Arguments to Functions 

### ISSUE THREAD

**Issue by Spenser309** [jenkinsci/JenkinsPipelineUnit#210]
Hi,

When I have a function in a shared library (var only) named utils.groovy

```
def testFunc(req_arg, opt_arg = "none") {
  echo "req_arg = ${req_arg}"
  echo "opt_arg = ${opt_arg}"
}
```

and I execute this in pipeline unit with a test like 

```
def execute() {
  utils.testFunc("req")
  utils.testFunc("req", "opt")
  utils.testFunc("req", opt_arg: "opt_map")
}

return this
```

And a test function of 
```
@Test
void req_opt_test() throws Exception {
    // Load Test Jenkinsfile
    def script = runScript("jenkinsfiles/req_opt_args.jenkins")
    // run
    script.execute()
    // Show call stack
    printCallStack()
    // assert that Job passes
    assertJobStatusSuccess()
}
```

I'm seeing a 
```
req_arg = req
opt_arg = none
req_arg = req
opt_arg = opt
req_arg = [opt_arg:opt_map]
opt_arg = req
```

Where req_arg is a map instead of a single value.

This also appears in the callstack as
```
      utils.testFunc(req)
         utils.echo(req_arg = req)
         utils.echo(opt_arg = none)
      utils.testFunc(req, opt)
         utils.echo(req_arg = req)
         utils.echo(opt_arg = opt)
      utils.testFunc({opt_arg=opt_map}, req)
         utils.echo(req_arg = [opt_arg:opt_map])
         utils.echo(opt_arg = req)
```

I was expecting
```
req_arg = req
opt_arg = none
req_arg = req
opt_arg = opt
req_arg = req
opt_arg = opt_map
```

**Comment by nre-ableton** [comment]
IMHO JenkinsPipelineUnit is doing the correct thing. When you call `utils.testFunc("req", opt_arg: "opt_map")`, `opt_arg` is being interpreted by Groovy as a `Map`, since it lacks an explicit type. You should instead declare `test_func` like so:

```groovy
def testFunc(String req_arg, String opt_arg = "none") {
  echo "req_arg = ${req_arg}"
  echo "opt_arg = ${opt_arg}"
}
```

**Comment by Spenser309** [comment]
why is the parameter order being altered?  

```
      utils.testFunc({opt_arg=opt_map}, req)
         utils.echo(req_arg = [opt_arg:opt_map])
         utils.echo(opt_arg = req)
```

I.e. why is the map not for opt_arg instead of req_arg?

**Comment by TobiX** [comment]
Because "named arguments" in Groovy don't work the way you assume they work. Whenever you use named arguments, Groovy puts them all into a Map and stuffs them into the first argument of the function: http://docs.groovy-lang.org/latest/html/documentation/#_named_parameters_2

For example, in your last test, you called:
```groovy
utils.testFunc("req", opt_arg: "opt_map")
```
but `opt_arg` isn't special at all and in no way related to the `opt_arg` you mentionen in your argument list.
```groovy
utils.testFunc("req", something_else: "opt_map")
```
still runs and puts `something_else: "opt_map"` into the map parameter of the function.

**Comment by stchar** [comment]
@TobiX thanks for the clarification. 
@Spenser309 I'm closing the issue, if you don't mind.
