### ISSUE TITLE
Is there a way to use this framework on premise?

### ISSUE THREAD

**Issue by Davis8988** [jenkinsci/JenkinsPipelineUnit#235]
I don't have an internet connection, but I am using Gitlab and Artifactory. I can copy things from the internet to our offline env. I don't how to make this awsome framework work in an offline env. Is it possible?

**Comment by stchar** [comment]
hi @Davis8988 
yes it is possible, all you need to do is to load all required dependencies and then copy gradle/maven caches to your env.

**Comment by TobiX** [comment]
If you have an internal Artifactory, you can mirror the Jenkins Maven repository:
![grafik](https://user-images.githubusercontent.com/78534/85139799-f966b700-b244-11ea-9c32-fe90b161300e.png)

And then use in your build.gradle:
```
repositories {
  maven { url 'https://my-internal-artifactory/maven-jenkins' }
  ...
}
```

(This is exactly the way I use it inside my company's network)
