### ISSUE TITLE
Failure to test shared library with libraryResource & writeFile

### ISSUE THREAD

**Issue by mathieudevos** [jenkinsci/JenkinsPipelineUnit#241]
Hey,

I have written a simple shared library to offload our "common" scripts to global variables. And now I wish to have some tests on this, which is where I seem to be stuck.

Folder structure:
```
|-- resources 
     |-- python
        |-+ foobar.py
|-- test
    |-+ foobarTest.groovy
|-- vars
    |-+ foobar.groovy
```

Contents of `resources/python/foobar.py`:
```python
#/usr/bin/env python

import sys

print "Hello ", sys.argv[1]
```

Contents of `foobar.groovy`:
```groovy
String call(String input) {
  String output = ''
  String pythonFileString = libraryResource('python/foobar.py')
  writeFile(file: 'foobar.py', text: pythonFileString)
  sh('chmod +x foobar.py')
  output = sh(returnStdout: true, script: "python foobar.py ${input}")

  // Additional Test Commands
  ls = sh(returnStdout: true, script: 'ls')
  pwd = sh(returnStdout: true, script: 'pwd')
  echo(ls)
  echo(pwd)

  return output
}
```

Contents of `foobarTest.groovy`:
```groovy
import org.junit.*
import org.junit.Rule
import static org.junit.Assert.*
import org.junit.rules.ExceptedException
import com.lesfurets.jenkins.unit.*

class FoobarTest extends BasePipelineTest {
  def foobar

  @Rule
  public ExpectedException thrown = ExceptedException.none()

  @Before 
  void setUp() {
    super.setUp()
    helper.registerAllowedMethod('writeFile', [Map.class], none) // This is needed otherwise I get MissingMethodException
  } 

  @Test 
  void 'Verify foobar functionality'() {
    def script = loadScript('vars/foobar.groovy')
    String output = script('test')
    printCallStack()
    assertEquals('Hello test', output)
  }
}
```

Running this test shows that it actually calls the right "writeFile" command (with the contents of the python file). However, all the other items are all null, thus failing the test: `AssertionError: expected: 'Hello test' but got 'null'`.

In the stacktrace I can also see is below:
```
foobar.call(test)
foobar.libraryResource(python/foobar.py)
foobar.writeFile({file=foobar.py, text=#/usr/bin/env python

import sys

print "Hello ", sys.argv[1]
})
foobar.sh(chmod +x foobar.py)
foobar.sh({returnStdout=true, script=python foobar.py test})
foobar.sh({returnStdout=true, script=ls})
foobar.sh({returnStdout=true, script=pwd})
foobar.echo(null)
foobar.echo(null)
```

Any ideas of what's happening here?

Am I just misunderstanding the mocking here? And if I am, is there an way make the unit tests **actually** execute the script provided here? Or is that a job for manual testing (writing a simple pipeline that uses this and actually runs the code)?

**Comment by nre-ableton** [comment]
Testing pipeline singletons is not exactly straightforward (IMHO). In the past, when my libraries had more singletons, we tested them like so:

```groovy
// vars/foobar.groovy
String thing() {
  return isUnix() ? 'yes' : 'no'
}
```

```groovy
// test/foobarTest.groovy
class thingTest extends BasePipelineTest {
  Object thing = null

  @Override
  @Before
  void setUp() {
    super.setUp()
    this.thing = new thing()
  }

  @Test
  void testDoStuff() {
    thing.isUnix = { return true }
    assertEquals('yes', thing.doStuff())
  }
}
```

IIRC, it is necessary to instantiate the singleton in a manner like this and set properties for the pipeline steps and such. I found this to be rather cumbersome and now use the following pattern in all of my pipeline libraries:

```groovy
// src/com/whatever/FooBar.groovy
class FooBar {
  Object script = null

  String doStuff() {
    assert script
    return script.isUnix() ? 'yes' : 'no'
  }
}
```

```groovy
// vars/fooBar.groovy
import com.whatever.FooBar

String doStuff() {
  return new FooBar(script: this).doStuff()
}
```

```groovy
// test/resources/EmptyPipeline.groovy
void execute() {
  node {
    stage('Empty') {}
  }
}

return this
```

```groovy
// test/com/src/FooBar.groovy
class FooBarTest extends BasePipelineTest {
  Object script = null

  @Override
  @Before
  void setUp() {
    super.setUp()
    this.script = loadScript('test/resources/EmptyPipeline.groovy')
    helper.registerAllowedMethod('isUnix', []) { return true }
  }

  @Test
  void doStuff() {
    assertEquals('yes', new FooBar(script: this.script).doStuff())
  }
}
```

So in other words, the `vars/*.groovy` singletons are basically empty wrappers, and all of the real code gets moved to proper classes in the `src` hierarchy. It's a bit more work, but offers some benefits which I think justify the approach.

One advantage of this organization is that it makes it easier to have multiple classes which may depend on each other. For example, you might have a `FooUtils` class which provides some extra general functionality, and you could create an instance of it from within `FooBar` using the `script` field. This also makes it easier inject mock objects during testing. All of these things become a bit trickier when just using singletons.

**Comment by stchar** [comment]
@mathieudevos it is possible to force `sh` mock to pass script to the shell which is applicable if you write an integration test, but not quite welcome in UnitTest layer

helper.registerAllowedMethod('sh', [Map], { args -> args.script.execute().text }) 
or any other solutions to call shell in groovy.

But keep in mind that this is adding some limitations to the test environment(os, python version and libs). However it is a great idea to use JPU for some integration testing.  

Another option is to mock `sh` to not to call a real shell but to pretend it does, the idea is to analyze the input and return an expected output. 
pros: environment independency, performance and so on 
cons: expected value could be different than in the real life 
```
helper.registerAllowedMethod('sh', [Map], { args -> 
  switch (args.script) {
    case ~/ls.*/ : return "dir1 dir2 file1"
    case ~/pwd/ : return "/mocked/home/dir"
    case ~/python foobar.py test/ : return "Hello test"
    default: return null
  } 
}) 
```

**Comment by stchar** [comment]
Pease let me know if you have any further questions.

**Comment by mathieudevos** [comment]
The answer with the `args.script.execute().text` is perfect for my wishes. Since I can run this on very basic files with just just python installed I can actually verify the output and run in depth unit tests on these.

Thanks for the assist!
