### ISSUE TITLE
How to mock docker.image('name').inside('params')

### ISSUE THREAD

**Issue by manthasiddartha** [jenkinsci/JenkinsPipelineUnit#242]

**Comment by nre-ableton** [comment]
[jenkins-pipeline-mocks](https://github.com/AbletonDevTools/jenkins-pipeline-mocks) provides a [DockerMock class](https://github.com/AbletonDevTools/jenkins-pipeline-mocks/blob/master/src/main/groovy/com/ableton/DockerMock.groovy) for this exact purpose.

**Comment by stchar** [comment]
@nre-ableton that's quite interesting project could please add an example how to use it?

**Comment by nre-ableton** [comment]
Sure! It's quite simple, really. Assuming that you've added `jenkins-pipeline-mocks` to `build.gradle`, you'd add it to the test class like so:

```groovy
class SomethingTest extends BasePipelineTest {
  Object script = null

  @Override
  @Before
  void setUp() {
    super.setUp()
    this.script = loadScript('test/resources/EmptyPipeline.groovy')
    script.docker = new DockerMock()
  }

  @Test
  void something() {
    new Something(script: script).doStuff()  // etc
  }
}
```

So the idea is that you need to provide an instance of the class on the script context which is passed to the tested class. You can also see a working example in the `postgres-pipeline-utils` library: https://github.com/AbletonDevTools/postgres-pipeline-utils/blob/master/test/com/ableton/PostgresDockerTest.groovy

**Comment by stchar** [comment]
@manthasiddartha, are you ok with the solution?

**Comment by nre-ableton** [comment]
@stchar Also, what would you think about possibly adding these mocks to this project? I know that in the past I have argued against third party library mocks, this library is so frequently used that we might want to make an exception.

If you're not opposed, I'd be happy to submit a PR.

**Comment by stchar** [comment]
@nre-ableton, I support any kind of improvement. Do you want to join sources or add it like a dependency?

**Comment by nre-ableton** [comment]
@stchar I'd rather not introduce a new dependency, instead I'll push sources. Also, my long term goal is to eventually deprecate our jenkins-pipeline-mocks repo and merge everything upstream here (where it makes sense, of course). I'll try to make a PR this week.

**Comment by nre-ableton** [comment]
@stchar Thanks!
