### ISSUE TITLE
Skip subsequent stages if stage fails

### ISSUE THREAD

**Issue by IncredibleLou** [jenkinsci/JenkinsPipelineUnit#243]
In Jenkins if a stage in the Jenkinsfile fails the other stages are not executed and a message like this is printed. 
"Stage "XY" skipped due to earlier failure(s)"

When I intercept one of the Jenkins steps like "sh" in my unit tests and update the build status to "FAILURE" all subsequent stages are still executed. 

Is there a possibility to simulate the behavior and skip the subsequent steps after one failed?

**Comment by stchar** [comment]
@IncredibleLou, good point, thank you! 

I think this logic could extended with a check for a build status
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/main/groovy/com/lesfurets/jenkins/unit/declarative/StageDeclaration.groovy#L47

Would you like to submit a pull request?

**Comment by IncredibleLou** [comment]
Sure. I guess this would be a breaking change as people currently using the library wouldn't expect this. Do you have a process in place for such changes?

**Comment by IncredibleLou** [comment]
#245

**Comment by IncredibleLou** [comment]
Here is my first draft. Works in my case. #245

**Comment by stchar** [comment]
merged, thank you.
