### ISSUE TITLE
Compiling pipeline DSL as Groovy class

### ISSUE THREAD

**Issue by ChastinaLi** [jenkinsci/JenkinsPipelineUnit#26]
Hello,

I have a generic Jenkins pipeline question, not entirely related to this repo.
I guess what I want to know is "if calling pipeline steps is possible outside the context of Jenkinsfile and Jenkins".
I would love to be able to compile shared pipeline libraries as normal Groovy code, but I get stuck all the time with dependencies and method signature issues.

I have the following code:
```groovy
package com.mycode;

def read(fileName) {
  return libraryResource(fileName)
}

return this
```
which wraps the [libraryResource](https://jenkins.io/doc/pipeline/steps/workflow-cps-global-lib/#code-libraryresource-code-load-a-resource-file-from-a-shared-library) step from the Jenkins pipeline DSL.
I wonder if there's a way to compile this class as a regular Groovy class? without being called by Jenkinsfile.

Thanks! ❤️ 🙏 🙇‍♀️

**Comment by ozangunalp** [comment]
Hi @ChastinaLi, 

I suggest you to take a look at https://jenkins.io/doc/book/pipeline/shared-libraries/#defining-shared-libraries.

Note that the functionalities in the "Loading libraries dynamically" section is not yet supported by JenkinsPipelineUnit.

Thanks.
