### ISSUE TITLE
Global Var with single argument gets IllegalArgumentException if caller passed NULL

### ISSUE THREAD

**Issue by Alex-Vol-SV** [jenkinsci/JenkinsPipelineUnit#260]
Having a Global Var with a single argument call will fail with IllegalArgumentException when the calling Jenkinsfile passes NULL in the argument list. This is not unusual and I traced the bug in the code that handles calling globals loaded from shared libraries.

I have a pull request prepared with the fix and will submit shortly.

This simple pipeline will cause the problem
```
@Library('commons@feature') _

// Test calling a one argument global with null
oneArg('Not null')
oneArg(null)
```

The oneArg.groovy global is just this simple method
```
// file: vars/oneArg.groovy
def call(arg) {
    if (arg == null) {
        echo "Is null"
    } else {
        echo "Is not null"
    }
}
```

**Comment by stchar** [comment]
Nice catch!
