### ISSUE TITLE
Env. and Params. values not accessible without proper prefix

### ISSUE THREAD

**Issue by Willem1987** [jenkinsci/JenkinsPipelineUnit#276]
In actual jenkins pipeline params and Env are accessible without their respective prefixes. This does not work in PipelineUnit, causing scripts that work on Jenkins to fail on unit test

**Comment by stchar** [comment]
Hi, thanks for the report, what's is the version of JenkinPipelineUnit?

**Comment by Willem1987** [comment]
Sorry, version 1.7. Newest released
