### ISSUE TITLE
Call method scripts don't extend anything?

### ISSUE THREAD

**Issue by Willem1987** [jenkinsci/JenkinsPipelineUnit#279]
In our vars folder we have groovy files which only import and have a call method.
(Like https://www.jenkins.io/doc/book/pipeline/shared-libraries/#defining-custom-steps)

This works fine in jenkins pipeline. We currently pass the this of the pipeline around to access sh and env vars in called scripts.
In Actual pipeline we can pass "this" as a CpsScript type. I tried using Script type for it, but it still won't recognize it.

Any suggestions on how to tackle this either changing the script of the pipelineunit?

I'm not sure if i want to change all my var scripts to be a class extending script

**Comment by nre-ableton** [comment]
Can you provide an example with your `vars` singleton? It's a bit unclear what the issue is here.

**Comment by Willem1987** [comment]
I apologize. It seems i was importing a script class other than just groovys. I can pass along my pipelinescript as Script type fine. Just not CpsScript as i originally used.
