### ISSUE TITLE
Calling method in agentdeclararion throws error

### ISSUE THREAD

**Issue by Willem1987** [jenkinsci/JenkinsPipelineUnit#280]
groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.declarative.AgentDeclaration.determineBranch() is applicable for argument types: () values: []

Consider this code:
kubernetes(k8sAgent(this, [label: "build-${moduleName}-${params.branch}",components: pipelineHelper.getComponents(determineBranch(),moduleName, 'build')]))

The method is declared in the file the pipeline is in and looks like:
private String determineBranch() {
    return params.targetBranch != null && !params.targetBranch.isEmpty() ? params.targetBranch : params
            .branch
}

In jenkins pipeline it manager to find the method, but in unit test it doesn't. Any suggestions?

**Comment by stchar** [comment]
Hi @Willem1987, there was a fix  #273 which allows objects of AgentDeclaration to access properties of pipeline script,
you can extend it using missingMethod via the metaclass to invoke pipeline methods

**Comment by Willem1987** [comment]
I am trying, but having a hard time figuring out how exactly. 

Upgraded Agent_bindings_JenkinsFile:
`
def AGENT = 'someLabel'

pipeline {
    agent none
    stages {
        stage('Example Build') {
            agent binding_var
            steps {
                echo 'Hello, Maven'
                sh 'mvn --version'
            }
        }
        stage('Example Test') {
            agent { docker binding_var }
            steps {
                echo 'Hello, JDK'
                sh 'java -version'
            }
        }
        stage('Example Release') {
            agent agentName()
            steps {
                echo "Deploy to ${AGENT}"
            }
        }
        stage('Example Deploy') {
            agent AGENT
            steps {
                echo "Deploy to ${AGENT}"
            }
        }
    }
}

private String agentName(){
    return AGENT;
}`

But keep getting missingMethodException
