### ISSUE TITLE
groovy.lang.MissingMethodException using script closure under steps in declarative pipeline

### ISSUE THREAD

**Issue by Willem1987** [jenkinsci/JenkinsPipelineUnit#283]
Example:
pipeline {
        stages {
            stage('Checkout from GIT') {
                steps {
                    script {

Error:
groovy.lang.MissingMethodException: No signature of method: buildFromGitlab.call() is applicable for argument types: 

It seems to want to call the script the pipeline is in?

**Comment by stchar** [comment]
Hi @Willem1987 
sorry. 
I don't quite follow you, could you please add some details( test and pipeline examples, stacktrace)

**Comment by Willem1987** [comment]
I though at first the script closure was causing the issue, but i cannot reproduce this with the Declarative_Jenkinsfile.

The line in the script block that is failing is :

sh("git config --global user.email 'jenkins-user@domain.org'")

I'm unsure why this is causing a call to the enclosing script.

**Comment by Willem1987** [comment]
The enclosing script "buildFromGitlab" is a groovy file with a call method. Not a full blown class. 
https://www.jenkins.io/doc/book/pipeline/shared-libraries/#defining-custom-steps

Though i see this might not have been meant for entire pipelines.

**Comment by Willem1987** [comment]
Okay, i found the issue.... This was my issue.

I added     def script = this in the script. Which was shadowing the script block.
