### ISSUE TITLE
 addMockSh only saves 1 response

### ISSUE THREAD

**Issue by Willem1987** [jenkinsci/JenkinsPipelineUnit#302]
For my use case i would like to allow to store a list of responses. In this case i'm testing a wait loop for a status to change.
I want to return stopped,starting,started.

**Comment by nre-ableton** [comment]
In this case, you should set a closure to be the return value and then do whatever you like inside of it.

**Comment by Willem1987** [comment]
Thankyou. That sounds like a good fix
