### ISSUE TITLE
Demo project

### ISSUE THREAD

**Issue by stchar** [jenkinsci/JenkinsPipelineUnit#31]
Hi, this is freaking awesome!!! Do you have a demo project?

**Comment by headcrabmeat** [comment]
Nevermind I think I founfd one =) https://github.com/ozangunalp/jenkins-pipeline-unit-example

**Comment by headcrabmeat** [comment]
((( It does't work

**Comment by ozangunalp** [comment]
Hi @headcrabmeat, 

it's been a while I did not update that repository. I'll make sure there are some relevant examples in it. 

Meanwhile you can take a look at the project itself. There are bunch of Junit test here : https://github.com/lesfurets/JenkinsPipelineUnit/tree/master/src/test/groovy/com/lesfurets/jenkins.

And @macg33zr has a nice example project which uses Spock in here : https://github.com/macg33zr/pipelineUnit

Hope that helps.

**Comment by headcrabmeat** [comment]
Cool, thanks
