### ISSUE TITLE
Help needed implementing custom agent definition

### ISSUE THREAD

**Issue by lehmannk** [jenkinsci/JenkinsPipelineUnit#316]
I have only started using this framework recently. I got stuck with a custom agent definition like such
```
agent {
    kubernetes {
      defaultContainer 'jnlp'
      cloud 'test-cloud'
      namespace 'cloud123'
      yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: helm
    image: rhel7
    tty: true
    command: [ cat ]
'''
    }
  }
```
The error I get is
```
groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.declarative.AgentDeclaration.kubernetes() is applicable for argument types: (Jenkinsfile$_run_closure1$_closure2$_closure5) values: [Jenkinsfile$_run_closure1$_closure2$_closure5@2bdd8394]
```
I know I have to provide my own method registration. However I don't know what class types to provide for `Jenkinsfile$_run_closure1$_closure2$_closure5`. I tried a generic approach with type `Object`
```
Consumer println = System.out::println;
getHelper().registerAllowedMethod(MethodSignature.method("kubernetes", Object.class), println);
```
but this does not help. Could someone point me to the right direction regarding the closure definition?

**Comment by nre-ableton** [comment]
I don't have the plugin available (nor am I terribly familiar with declarative pipelines), but I'm guessing it takes a Map instead of an Object, so you would want to do:

```groovy
registerAllowedMethod('kubernetes', [Map]) { println }
```

**Comment by lehmannk** [comment]
In fact, I even tried the Map implementation first and it did not work. I am confused what the framework means with `Jenkinsfile$_run_closure1$_closure2$_closure5`

**Comment by nre-ableton** [comment]
Ahhh, I see, the problem is that you are passing a _closure_ to it. So your mock should be:

```groovy
registerAllowedMethod('kubernetes', [Closure]) { println }
```

**Comment by lehmannk** [comment]
works now, I updated to v1.8 and have no more issues.

**Comment by nre-ableton** [comment]
Great, glad to hear you got it sorted out!
