### ISSUE TITLE
Can't quite figure out how the mocking works

### ISSUE THREAD

**Issue by wheelerlaw** [jenkinsci/JenkinsPipelineUnit#317]
So lets say I have a script (src/org/cvp/pipeline/CvpUtils.groovy) in my shared library that defines a series of functions: 

```groovy
def testMethod(String param) {
    def string = mockedMethod(param)
    print(string)
}

def mockedMethod(String param) {
    return param
}
```
If I try to run the following tests, I keep getting `hello` as the output, whereas I would expect `world` (since I am mocking one of the functions):

```groovy
package org.cvp.pipeline

import com.lesfurets.jenkins.unit.BasePipelineTest
import org.junit.Before
import org.junit.Test


class CvpUtilsTest extends BasePipelineTest{

    private Script script

    @Override
    @Before
    void setUp() throws Exception{
        scriptRoots = ['src', 'vars']
        super.setUp()
        script = loadScript("org/cvp/pipeline/CvpUtils.groovy")
    }

    @Test
    void test_createISVContainerVerificationTestTriggerMap() {
        helper.registerAllowedMethod("mockedMethod", [], {"world"})
        script.testMethod("hello")
    }
}
```

I added a mock for `mockedMethod` to return something different (`world`), however, it would appear that it is still returning `hello`. How do I mock out custom methods in scripts?

**Comment by nre-ableton** [comment]
In your example, the method you are trying to mock takes a string, not void. You should register your mock like:

```groovy
helper.​registerAllowedMethod(​"​mockedMethod​"​, [String], {​"​world​"​})
```

**Comment by reinholdfuereder** [comment]
@wheelerlaw I guess the hint from @nre-ableton works?
=> Can this issue therefore be resolved?
