### ISSUE TITLE
runSh bails out too early when requested to finish with error code.

### ISSUE THREAD

**Issue by apogrebnyak** [jenkinsci/JenkinsPipelineUnit#327]
Real `sh` step when run with `returnStdout:true` argument, will still finish with error when script inside `sh` returns non-0 status.

However, because of this logic
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/a469daf904e8c8e9957dea6e2eea9c59150fd9e2/src/main/groovy/com/lesfurets/jenkins/unit/PipelineTestHelper.groovy#L691

the mocked version of `sh` bails out too early, and no exception is thrown upon error exit status.

**Comment by nre-ableton** [comment]
Yes, you're right, this seems to be the correct behavior. Please see https://github.com/jenkinsci/JenkinsPipelineUnit/pull/329.
