### ISSUE TITLE
BasePipelineTest.addParam throws MissingPropertyException if you not manually add `params` map to the binding

### ISSUE THREAD

**Issue by apogrebnyak** [jenkinsci/JenkinsPipelineUnit#331]
Despite the fact that method tries to deal with missing `params` property here
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/a469daf904e8c8e9957dea6e2eea9c59150fd9e2/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L437

The `binding.getVariable` will throw `MissingPropertyException` and not return `null` if you did not set `params` variable preeviously.

Looks like you need to call `binding.hasVariable` first in order to lazy initialize `params`.

**Comment by nre-ableton** [comment]
Related: https://github.com/jenkinsci/JenkinsPipelineUnit/pull/321
