### ISSUE TITLE
Mocking shared lib methods with multiple args

### ISSUE THREAD

**Issue by martingrosche** [jenkinsci/JenkinsPipelineUnit#337]
I'm unit testing a shared library especially a script of the vars part.
The script `vars/myScript.groovy` has the following structure:
```groovy
def call(){
	foo('arg1', 'arg2', 'arg3')
}

def foo(arg1, arg2, arg3){
	// do some magic

	bar(arg1)

	// do some magic again

	fooBar(arg2, arg3)
}

def bar(arg){
	println("Calling bar with argument: ${arg}.")
}

def fooBar(arg1, arg2){
	println("Calling fooBar with arguments: ${arg1} and ${arg2}.")
}
```

The test `MyScriptTest.groovy` is looking like this.
```groovy
class MyScriptTest extends BasePipelineTest {
	def myscript
	
	def setup() {
		myscript = loadScript('vars/myscript.groovy')
	}

	def 'Test method foo'
		given:
			// this work really well
			helper.registerAllowedMethod('bar', [Object],
                    { println("mocking bar") })
			// this does not work at all
			helper.registerAllowedMethod('fooBar', [Object, Object],
                    { println("mocking fooBar") })
			// finally i've to load the script again to register all methods correctly
			myscript = loadScript('vars/myscript.groovy')
		
		when: 
            myscript.foo('mArg1', 'mArg2', 'mArg3')

		then:
			// do some checks for the foo magic 
}
```
It seems to have something to do with the number of arguments. 
Is there another way to mock / register second level methods with multiple arguments. 
Am I doing something wrong? Or is there a bug?

Thanks

**Comment by nre-ableton** [comment]
Can you please share the exception that you are seeing when you try to run these tests?

**Comment by martingrosche** [comment]
There is no exception in case of the example but the print is not the expected one.
```
expected:    "mocking fooBar"
out:              "Calling fooBar with arguments: mArg2 and mArg3."

**Comment by nre-ableton** [comment]
Just out of curiosity, would it make a difference if you used the exact types? So in other words, `helper.registerAllowedMethod('fooBar', [String, String], ...`

**Comment by martingrosche** [comment]
No, it does not make any difference. I have already checked this before creating the issue.

**Comment by martingrosche** [comment]
Hallo
are there any updates or known workarounds regarding the issue?

**Comment by nre-ableton** [comment]
Sorry, I am not sure what the issue is here and haven't had time to try and reproduce them locally. I'll try to do that in the next few days and report back.

**Comment by nre-ableton** [comment]
Ok, I've looked into this issue a bit more and can't find anything wrong. I have a few suggestions for how we may continue to investigate:

- Use type declarations in your function signatures, so instead of `foo(arg1, arg2, arg3)`, `foo(String arg1, String arg2, String arg3)` (or at a very minimum, `def`).
- If your example is based on production code, it might be more useful for us to see the actual code which is generating these errors (with any confidential details removed, of course). Sometimes people make bug reports with simplified versions of failing code, but we may need to see more context to see what is going on.

**Comment by martingrosche** [comment]
Sorry for getting back so late, unfortunately the issue has gone a bit out of focus.
Using type declaration has no effect. It seems to me to have something to do with the fact that the fooBar is called inside foo.

* if I mock foo (3 arguments) then it works with multiple arguments.
* if I mock bar (1 argument) called as child (see code above) than it works
* if I mock fooBar (2 arguments) called as child (see code above) than doesn't it work

You can use the code above in any environment to reproduce 👍

**Comment by martingrosche** [comment]
Just fyi: To mock methods with multiple args like
``` java
helper.registerAllowedMethod('fooBar', [Object, Object],
                    { println("mocking fooBar") })
``` 
It has to be changed to 
``` java
helper.registerAllowedMethod('fooBar', [Object, Object],
                    { arg1, arg2 -> println("mocking fooBar") })
```
Since groovy handles `one` argument as an implicit parameter (`it`) it works fine without any explicit definition.
