### ISSUE TITLE
How to register methods with more than one arguments

### ISSUE THREAD

**Issue by Ashissh021** [jenkinsci/JenkinsPipelineUnit#344]
I am kind of new to Jenkins pipeline Unit test mocking and i am looking into help for below scenario
Description: I have Jenkins file in that we have some method call(method is in library) like myMethod(), I want to right test case in such a way like it should method Name and check that method is in allowed list then it should not throw error and also it should ignore the arguments is passed or not or if its passed more than one arguments, it should ignore. 
Also if that method like myMethod() is groovy file and in that we have different method in it so that should also pass like below  
myMethod.groovy
    | ------call()
    |----smallMethod()
    |---bigMethod()   

so if i call from jenkins file like below
stage('my method check'){
  steps{
    script{
    myMethod()
   myMethod.smallMethod()
   myMethod.smallMethod('hello')
   myMethod.smallMethod('hello', 'args2')
   }
  }
}
everything should be pass.
I tried this approach but its not working 
https://github.com/jenkinsci/JenkinsPipelineUnit#mock-jenkins-commands

please help if anyone got some idea so
Thanks in Advances

**Comment by pojacque** [comment]
Hello all, I have a similar use case. 

I want to use `registerAllowedMethod` somewhat generically to support any overloaded version of  `smallMethod`(as in your example @Ashissh021).

I realize the manual way to go about this is to register each version of what we want to support. For example the `readFile` mocks on [BasePipelineTest](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/ce22e785c577d54fff63976621477d1bf2f6ea08/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L186):
```
        helper.registerAllowedMethod('readFile', [Map], { args -> helper.readFile(args) })
        helper.registerAllowedMethod('readFile', [String], { args -> helper.readFile(args) })
```
But I don't think there is a way to have this done yet.

Could we re-open this ticket and make it about **How to register overloaded methods**?

**Comment by nre-ableton** [comment]
@pojacque If I understand you correctly, overriding mocks can simply be done in your setup method, like so:

```groovy
@Override
@Before
void setUp() {
  super.setUp()  // Will register mocks from BasePipelineTest
  helper.registerAllowedMethod('readFile', [Map]) { echo 'my override!' }
}
```

The above code will effectively re-route `readFile(Map)` from the default mock in `BasePipelineTest` to the one above.

**Comment by pojacque** [comment]
@nre-ableton Hi Nick! I edited my previous post to expand on the `smallMethod` example.

The repetition I'm trying to avoid is, instead of having to register each version like:
```groovy
helper.registerAllowedMethod('smallMethod', [], {'mock of smallMethod'}) // mocks the no-param version
helper.registerAllowedMethod('smallMethod', [Object], {'mock of smallMethod'}) // mocks the one-arg version
helper.registerAllowedMethod('smallMethod', [Object, Object], {'mock of smallMethod'}) // mocks the two-arg version 
// etc etc

```
Into some magic short-hand version 
 ```
 helper.registerAllowedOverloadedMethod('smallMethod', {'This mock should intercept any params!'}) 
 ```

I hope the example explains better the functionality that I wish it existed.

**Comment by nre-ableton** [comment]
Ah, ok, I see what you mean here. Sorry for the misunderstanding. Yes, there is presently no way to do this on the library. Let's instead open a new issue to discuss this.

**Comment by nre-ableton** [comment]
@pojacque See https://github.com/jenkinsci/JenkinsPipelineUnit/issues/345. Please feel free to add more information there, if you think I've missed something.
