### ISSUE TITLE
Allow `addShMock` to take Pattern

### ISSUE THREAD

**Issue by JorisBolsens** [jenkinsci/JenkinsPipelineUnit#347]
It would be very useful to be able to add pattern matching to the sh mock, something like

```groovy
def p = ~"echo *."
helper.addShMock(p) { s ->
  println(s.replace('echo ',''))
}
```

**Comment by nre-ableton** [comment]
This seems like an interesting idea, and probably not super difficult to implement. Preserving backwards compatibility might be a bit of a concern, though. Existing unit tests which call `addShMock` do not assume that the strings passed in will be interpreted as regexps, which could result in some unexpected errors. We might need to add an extra parameter (or override) to prevent this.

Anyways, I'll take a look at this feature when I have some spare time or hack day.

**Comment by nre-ableton** [comment]
Fixed by https://github.com/jenkinsci/JenkinsPipelineUnit/pull/498
