### ISSUE TITLE
Timeout mock is broken when invoking with `Integer, Closure`

### ISSUE THREAD

**Issue by nre-ableton** [jenkinsci/JenkinsPipelineUnit#351]
It seems that https://github.com/jenkinsci/JenkinsPipelineUnit/pull/294 is broken somehow -- when trying to use that mock, an exception is thrown similar to the following:

```
groovy.lang.MissingMethodException:
No signature of method: com.lesfurets.jenkins.unit.BasePipelineTest$_registerAllowedMethods_closure26.call()
is applicable for argument types: (java.lang.Integer, com.ableton.Example$_exampleMethod_closure3$_closure5) values:
[60, com.ableton.Example$_exampleMethod_closure3$_closure5@3300f4fd]
```

I have no idea why this is happening, since the registration of the mock looks to be legit.

**Comment by gulyas-istvan-netlock-hu** [comment]
Hello @nre-ableton !

Please check:
https://github.com/jenkinsci/JenkinsPipelineUnit/pull/294#pullrequestreview-677402884
