### ISSUE TITLE
Cannot load a step when testing a shared library

### ISSUE THREAD

**Issue by giorgiosironi** [jenkinsci/JenkinsPipelineUnit#37]
I am testing my Jenkins shared library, in https://github.com/elifesciences/elife-jenkins-workflow-libs/blob/master/src/test/groovy/TestElifeNewRelicEnsureStatus.groovy I execute, in the test:
```
def script = loadScript("vars/elifeNewRelicEnsureStatus.groovy")
System.out.println(script);
```
I get this output:
```
TestExampleJob > should_execute_without_errors STANDARD_OUT
    null
```
What is the correct way to load a shared step and execute it? I saw some `return this` statements in other places but they return a complex object, doesn't seem to solve the problem.

**Comment by ozangunalp** [comment]
Hi @giorgiosironi,

Shared libraries are not loaded the same way as pipeline scripts. 

You can test shared libraries as described in here [https://github.com/lesfurets/JenkinsPipelineUnit#testing-shared-libraries]. 

The idea is that you register your shared library to the framework with its name and where to search for its source code. Than, you can load and test scripts that use this shared library with `@Library("...")`, global vars etc. 

Btw, the name of the `loadScript` method is misleading, it loads AND runs the script and returns the return value of it. I am planning to change this in the future to split as `load` and `run`.

In many examples of test we define a principal method (`execute`) in the script and return itself with `return this`. Than you can invoke execute method to the returning script object. 

You can find an example test using shared libraries in here : 
[https://github.com/lesfurets/JenkinsPipelineUnit/blob/master/src/test/groovy/com/lesfurets/jenkins/TestSharedLibrary.groovy]

I hope it is clear enough.

**Comment by giorgiosironi** [comment]
Ok, my use case is a bit different: adding tests to a shared library so that I can run a test suite on it before pushing it into Jenkins and possibly breaking downstream builds. Is that possible?

**Comment by bguerin** [comment]
@giorgiosironi I do exactly this, but with release 0.12 of this framework.

Before the 1.0 release, the _loadScript()_ method returned the _Script_, on which you can call _invokeMethod()_, if needed with parameters, and then assert that your script respond as wanted.

Something like :
```
    @Test
    public void should_recognize_maintenance_branches() throws Exception {
        final Script script = loadScript("vars/versionUtils.groovy");

        assertThat(script.invokeMethod("isMaintenanceBranch", null)).isEqualTo(false);
        assertThat(script.invokeMethod("isMaintenanceBranch", "")).isEqualTo(false);
        assertThat(script.invokeMethod("isMaintenanceBranch", "master")).isEqualTo(false);
        assertThat(script.invokeMethod("isMaintenanceBranch", "1.2")).isEqualTo(true);
    }
```

**Comment by SpencerMalone** [comment]
+1 on the idea of testing shared libraries in CI. In many ways, that's more important to me than testing individual Jenkinsfiles.

**Comment by pteichner** [comment]
@SpencerMalone I would agree - the shared library will affect all your pipelines using it whilst the Jenkinsfile will "only" be for one thing see issue https://github.com/lesfurets/JenkinsPipelineUnit/issues/47

**Comment by headcrabmeat** [comment]
Personally I prefer to treat a shared library as a separate module. So I can create it's own test harness using this project to cover it's internals with unit tests. However in pipelines I actually mock any calls for the shared library it uses which I think a kinda right thing.

So anyway You can find any examples of unit-test in this repository, or you can see my project https://github.com/headcrabmeat/pipeline-sharedlib-testharnes. I use it as a template for my libs.

**Comment by rmisra1234** [comment]
@headcrabmeat Thanks for sharing your sample project, very helpful. Any idea how to provide dummy values for local variables e.g. issues ? :

`def issues = script.jiraJqlSearch([jql: "Component=${moduleName}&Created>-24h"])                                                
`
` script.echo "Number of existing defects for this module "+issues.data.total.toString()`


I am mocking the jiraJqlSearch method as below but then the line issues.data.total.toString() throws an exception as "issues" is null:

`
helper.registerAllowedMethod("jiraJqlSearch", [Map.class], null)
`

**Comment by rmisra1234** [comment]
Found the answer to my own question:

`helper.registerAllowedMethod("jiraJqlSearch", [Map.class], { c -> [data:[total:"1"]] })`

**Comment by SpencerMalone** [comment]
Re: "I want to test all the shared libraries". Tangentially related to this issue, but it got a lot of support. I realized that I was looking for integration tests more than unit tests, so that I could test actual plugin versions and jenkins core versions. With that in mind, I spun up https://github.com/SpencerMalone/JenkinsPipelineIntegration.

**Comment by gautamdivgi** [comment]
Is there a way to use the jar files for the plugins and register them as allowedMethods? E.g. 
```
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>pipeline-utility-steps</artifactId>
            <version>2.2.0</version>
        </dependency>        
```
has readYaml, writeYaml, etc. While these can be mocked they do not need to be. Similarly using
```
sh ( script: ```echo abc```, returnStdout: true )
```
Technically I could add the maven dependencies in my project. Bu I currently lack the knowledge of how these can be selectively added as closures for the groovy calls.

**Comment by stchar** [comment]
@gautamdivgi I haven't seen such examples of how to wrap classes which implements SimpleBuildStep interface into `registerAllowedMethod`. You have to shadow plugin logic to test your pipelines

If you'd like to verify how your pipelines integrates with jenkins plugins you can try to use `@JenkinsRule` which is a part of jenkins test framework (see https://jenkins.io/doc/developer/testing/)

There is a gradle plugin https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin which would help to setup test environment

See examples:
https://github.com/mkobit/jenkins-pipeline-shared-library-example
https://github.com/stchar/pipeline-sharedlib-testharness

**Comment by stchar** [comment]
@gautamdivgi 
Please also take look at #78
