### ISSUE TITLE
Timeout for gitSource retriever is too short

### ISSUE THREAD

**Issue by GordonJess** [jenkinsci/JenkinsPipelineUnit#373]
### Version report

Jenkins and plugins versions report:

```
Jenkins 2.249.1
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Windows 10 (64-bit)
```

### Reproduction steps

- Define and register a shared library using the `gitSource` retriever as part of a test
- Run the test

### Results

Expected result:

The defined library is cloned and loaded for use by the test

Actual result:

Test fails when the repository cloning takes longer than 10 seconds:

```
[ERROR] executes without errors(PipelineSpec)  Time elapsed: 12.837 s  <<< ERROR!
com.lesfurets.jenkins.unit.global.lib.LibraryLoader$LibraryLoadingException: Error on loading library my-shared-lib@master : process has not exited
	at PipelineSpec.setup_closure2(pipelineSpec.groovy:59)
	at PipelineSpec.runScript(pipelineSpec.groovy:20)
	at PipelineSpec.executes without errors(pipelineSpec.groovy:99)
Caused by: java.lang.IllegalThreadStateException: process has not exited
	at PipelineSpec.setup_closure2(pipelineSpec.groovy:59)
	at PipelineSpec.runScript(pipelineSpec.groovy:20)
	at PipelineSpec.executes without errors(pipelineSpec.groovy:99)
```

**Comment by nre-ableton** [comment]
This is because `BasePipelineTest` does not register a default mock for `gitSource`. You can do so in your tests like so:

```groovy
@Override
@Before
void setUp() {
  super.setUp()
  helper.registerAllowedMethod('gitSource', [Map]) {}
}
```

This is of course assuming that `gitSource` is declared as `def gitSource(Map args)`. I have no idea if that's actually the case -- what plugin provides the `gitSource` step anyways? It doesn't seem to be part of the standard pipeline steps (unless I am mistaken?).

**Comment by GordonJess** [comment]
Sorry for the confusion.  I am testing a pipeline script which uses a shared library and I want to register that library so it can be used by the pipeline code being tested.  The [gitSource](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/6d4315768c5568ea3d9ad75625e0745eca9d4be5/src/main/groovy/com/lesfurets/jenkins/unit/global/lib/GitSource.groovy#L34) that I am referring to is the retriever used in definition of this library:

```
def library = library(libraryName)
                        .retriever(gitSource('ssh://git@my-server/my-project/my-repo.git'))
                        .defaultVersion("master")
                        .targetPath(libraryName)
                        .allowOverride(true)
                        .implicit(false)
                        .build()
helper.registerSharedLibrary(library)
```

This retriever [sets a timeout of 10 seconds](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/6d4315768c5568ea3d9ad75625e0745eca9d4be5/src/main/groovy/com/lesfurets/jenkins/unit/global/lib/GitSource.groovy#L29).  Just for comparison, the default timeout for cloning with the scm-steps plugin is 10 minutes.

**Comment by nre-ableton** [comment]
Ah, ok, sorry, I see what you mean now. I've opened a PR to fix this: https://github.com/jenkinsci/JenkinsPipelineUnit/pull/377. Thanks for noticing this!

**Comment by GordonJess** [comment]
Hi @nre-ableton,

Is there anywhere I can get hold of the current development version of JenkinsPipelineUnit?  Or any estimation for the date of next release? This issue is blocking me quite a bit as it sporadically causes all of my tests to fail.

**Comment by nre-ableton** [comment]
Sure, I can release 1.10 today. There's a handful of other fixes which I guess could be released as well.

**Comment by GordonJess** [comment]
Amazing, thank you!

**Comment by nre-ableton** [comment]
@GordonJess Sorry for the delay, I had some issues with my jenkins.io account. Anyways, version 1.10 has been published and should be available from the Jenkins artifactory repository now.

**Comment by GordonJess** [comment]
@nre-ableton No worries, and thank you, much appreciated!  It's not showing yet on MavenRepository, but it's definitely there, I managed to pull it :)
