### ISSUE TITLE
nested call method without mock

### ISSUE THREAD

**Issue by Yihan1993** [jenkinsci/JenkinsPipelineUnit#374]
Hi I'm new to the JenkinsPipelineUnit, I have some problem with the following usecase.
I build the project with gradle and JeninsPipelineUnit version is 1.9 testImplementation 'com.lesfurets:jenkins-pipeline-unit:1.9'

assume that:
in **vars/runScript.groovy** 
```groovy
Object call(Map argConfig)
{
  return { someVaule}
}
```

in **vars/conanExt.groovy** 
```groovy
void foo(Map argConfig)
{
  // use runScript call function here
  runScript(argConfig)
}
```
in **test/ConanExtTest.groovy:**
```groovy
class ConanExtTest extends BasePipelineTest {
  def conanExt
  def argConfig = [ : ]

  // Before every testcase is run, do this
  @Before
  void setUp() {
    super.setUp()
    // Load the script, without executing it
    conanExt = loadScript('vars/conanExt.groovy')
  }

  @Test
  void testFoo() {
    conanExt.Foo(argConfig)
    printCallStack()
  }
```

Error report 
**groovy.lang.MissingMethodException: No signature of method: conanExt.runScript() is applicable for argument types: (LinkedHashMap) values:**

I try to add `binding.setVariable('runScript', loadScript('vars/runScript.groovy'))` in `setUp()` method, still get the same error.
Seems like I could only use the runScript() method with `runScript.call()` in the **conanExt.groovy** file.
Could someone give me a Idea how could directly use the runScript method, without mock it with 
`helper.registerAllowedMethod()` ?

**Comment by nre-ableton** [comment]
If I'm not mistaken, you might need to load `runScript` as well. So in other words:

```
@Before
void setUp() {
  super.setUp()
  conanExt = loadScript('vars/conanExt.groovy')
  conanExt.runScript = loadScript('vars/runScript.groovy')
}
```

**Comment by Yihan1993** [comment]
@nre-ableton So at first, thanks a lot for your reply!
Let me change the question,
assume in **vars/runScript.groovy**:
```
Object call(Map argConfig)
{
  return { someVaule }
}
```
and in test file **test/RunScriptTest.groovy**
```
class RunScriptTest extends BasePipelineTest {

  // The class under test
  def runScript

  // Before every testcase is run, do this
  @Before
  void setUp() {
    super.setUp()
    // Load the script, without executing it
    runScript = loadScript('vars/runScript.groovy')
  }


  // Testcase
  @Test
  void testCall() {
    Map argConfig = [:]
    runScript(argConfig)
    printCallStack()
  }
}
```
The error report: **No signature of method: RunScriptTest.runScript() is applicable for argument types: (LinkedHashMap) values:**

and if I change the `runScript(argConfig)` to `runScript.call(argConfig)` in the test file. It works.

So I'm confussing why I need to use `.call()` to run the method?
here is the configuration in **build.gradle** file
```
    testImplementation 'junit:junit:4.12'
    testImplementation 'com.lesfurets:jenkins-pipeline-unit:1.9'
```

**Comment by Yihan1993** [comment]
> @nre-ableton So at first, thanks a lot for your reply!
> Let me change the question,
> assume in **vars/runScript.groovy**:
> 
> ```groovy
> Object call(Map argConfig)
> {
>   return { someVaule }
> }
> ```
> 
> and in test file **test/RunScriptTest.groovy**
> 
> ```groovy
> class RunScriptTest extends BasePipelineTest {
> 
>   // The class under test
>   def runScript
> 
>   // Before every testcase is run, do this
>   @Before
>   void setUp() {
>     super.setUp()
>     // Load the script, without executing it
>     runScript = loadScript('vars/runScript.groovy')
>   }
> 
> 
>   // Testcase
>   @Test
>   void testCall() {
>     Map argConfig = [:]
>     runScript(argConfig)
>     printCallStack()
>   }
> }
> ```
> 
> The error report: **No signature of method: RunScriptTest.runScript() is applicable for argument types: (LinkedHashMap) values:**
> 
> and if I change the `runScript(argConfig)` to `runScript.call(argConfig)` in the test file. It works.
> 
> So I'm confussing why I need to use `.call()` to run the method?
> here is the configuration in **build.gradle** file
> 
> ```groovy
>     testImplementation 'junit:junit:4.12'
>     testImplementation 'com.lesfurets:jenkins-pipeline-unit:1.9'
> ```

I think I found the reason.
firstly `Object call(Map argConfig)` has return value, so it cannot be called implicitly.
secondly in testcase the variable `runScript` is also defined in `BasePipelineTest`, this also seems to affect implicit calls.

so when I change the variable name `runScript` to `test` in **test/RunScriptTest.groovy** and also remove the return value in **vars/runScript.groovy** like following
```groovy
void call(Map argConfig)
{
  println "hello world"
}
```
I could use call the method with `test(argconfig)` in **test/RunScriptTest.groovy**
