### ISSUE TITLE
How to effectly mock Jenkins.instance or other hudson.model class

### ISSUE THREAD

**Issue by Yihan1993** [jenkinsci/JenkinsPipelineUnit#375]
releate to the https://github.com/jenkinsci/JenkinsPipelineUnit/issues/309
I have a similar usecase
```groovy
def Channel = Jenkins.getInstance().getComputer(env.NODE_NAME).getChannel()
def BasePath = new FilePath(Channel, pwd())
```
here the problem is that for FilePath constructor it has to use the following template
```groovy
FilePath(FilePath base, String rel)
FilePath(hudson.remoting.VirtualChannel channel, String remote)
```
I don't know how to mock the jenkins interface `VirtualChannel` so I write my `JenkinsMock.groovy` Class as followed
```groovy
//region Classes

// Mock Jenkins Class
class JenkinsMock {

  // Mock Class variables
  def Channel

  // Reset all the variables to default values
  void resetAllVariables() {
    Channel = new FilePath (new File('dummyChannel'))
  }

  //region wrap methods

  // Wraps the getInstance method
  JenkinsMock getInstance() { return this }

  // Wraps the getComputer method
  JenkinsMock getComputer(String nodeName) { return this }

  // Wraps the getChannel method
  FilePath getChannel() { return Channel }

  //endregion
}
```
So in my JenkinsMock Class I used return Channel as a FilePath class so that I could used the `FilePath(FilePath base, String rel)` as constructor. But I think this solution is really bad...
By the way, in our project, we used many Jenkins API, like `Job` `build` `JobOwnerHelper`... I would like to ask if you have a better way to mock those class or could we directly use the original Jenkins API and do something like: 
`mock(JobOwnerHelper.class)`
because currently I have to create mock class for each Jenkins API, which is really inconvenient

Thanks!

**Comment by GordonJess** [comment]
I'm also having problems with this.  I'm trying to add a Spock Stub for `Jenkins.getInstance()` but it always returns `null`.  Stubbing most other methods works fine, but I've found that `Jenkins.get()` is also problematic.  Any ideas?

```groovy
import jenkins.model.Jenkins

def instance = Mock(Jenkins)
def jenkins = Stub(Jenkins){
    getInstance() >> instance // always returns null
    getRawBuildsDir() >> "test" // works fine
}
binding.setVariable("Jenkins", jenkins)
```

**Comment by GordonJess** [comment]
It's only the static methods I have trouble stubbing so I expect the class's original methods are always run instead of those of my Stub.  Maybe using `GroovySpy` here can help to [mock static methods](https://spockframework.org/spock/docs/1.1-SNAPSHOT/all_in_one.html#_mocking_static_methods).

**Comment by GordonJess** [comment]
I solved by wrapping the access to `Jenkins` in another method, and then adding a stub for that method to return the mock.

In the pipeline:
```groovy
def getJenkinsInstance() {
    Jenkins.getInstance()
}
```

In the test specification:
```groovy
def jenkins = Stub(Jenkins)
helper.registerAllowedMethod("getJenkinsInstance", [], { return jenkins })
```

**Comment by Yihan1993** [comment]
> I solved by wrapping the access to `Jenkins` in another method, and then adding a stub for that method to return the mock.
> 
> In the pipeline:
> 
> ```groovy
> def getJenkinsInstance() {
>     Jenkins.getInstance()
> }
> ```
> 
> In the test specification:
> 
> ```groovy
> def jenkins = Stub(Jenkins)
> helper.registerAllowedMethod("getJenkinsInstance", [], { return jenkins })
> ```
Thanks a lot for you reply and sample code. I solved it with a similar way through using the `groovy.mock.interceptor.MockFor`
See https://www.groovy-lang.org/testing.html#_mocking_and_stubbing
Here is the sample code from my solution
```groovy
import groovy.mock.interceptor.MockFor
import jenkins.model.Jenkins

  @Before
  void setUp() {
    super.setUp()
    // Load the script, without executing it
    Foo= loadScript('vars/foo.groovy')
  }

  // Testcases
  @Test
  void testFoo() {
    def mockJenkins = new MockFor(Jenkins.class)
    mockJenkins.demand.getInstance { Jenkins.class }
    mockJenkins.use {
      // Jenkins.getInstance could be used in foo.groovy file
      foo()
    }

    printCallStack()
  }
```

**Comment by famod** [comment]
FWIW, I was able to simply static-mock `Jenkins.get()` via Mockito. I didn't need a separate method in my pipeline.

```java
    private Jenkins jenkinsMock
    private MockedStatic<Jenkins> jenkinsStatic

    @BeforeEach
    void setUpThis() {
        // mock Jenkins.get() to return a mock which can futher stubbed later on via the jenkinsMock field
        // could be moved to CpsTestSupport if needed elsewhere
        jenkinsMock = mock(Jenkins)
        jenkinsStatic = mockStatic(Jenkins)
        jenkinsStatic.when({ Jenkins.get() }).thenReturn(jenkinsMock)
    }

    @AfterEach
    void tearDown() {
        jenkinsStatic?.close()
    }
```
