### ISSUE TITLE
Example for using shared declarative pipelines?

### ISSUE THREAD

**Issue by red8888** [jenkinsci/JenkinsPipelineUnit#380]
This is my test (copied from the snippets in the docs)

```
package vars

import org.junit.Before
import org.junit.Test
import com.lesfurets.jenkins.unit.declarative.*

class ExampleDeclarativePipelineTest extends DeclarativePipelineTest {
  // Setup environment for running unit tests
  @Override
  @Before
  public void setUp() throws Exception {
    super.setUp();
  }

  @Test
  public void should_execute_without_errors() throws Exception {
      //def script = runScript("vars/exampleDeclarativePipeline.groovy")
      def script = runScript("vars/Jenkinsfile")
      assertJobStatusSuccess()
      printCallStack()
  }
}
```

That works if I have an actual Jenkinsfile, but I defined my pipeline in my shared library (common pattern at this point) and it looks like this:

```
def call(Map config) {
    pipeline {
        agent none
        stages {
            stage('Example Build') {
                agent { docker 'maven:3-alpine' }
                steps {
                    echo 'Hello, Maven'
                    sh 'mvn --version'
                }
            }
            stage('Example Test') {
                agent { docker 'openjdk:8-jre' }
                steps {
                    echo 'Hello, JDK'
                    echo 'Hello, JDK'
                    echo 'Hello, JDK'
                    echo 'Hello, JDK'
                    echo 'Hello, JDK'
                    sh 'java -version'
                }
            }
        }
    }
}
```

If I point my test to this groovy script (`def script = runScript("vars/exampleDeclarativePipeline.groovy")` ) it seems to do nothing. I don't get a stack trace or anything. 

How can I test my shared pipeline code? 

Thanks!

**Comment by Yihan1993** [comment]
maybe try `def script = loadScript("vars/exampleDeclarativePipeline.groovy")`?

**Comment by red8888** [comment]
loadScript() isnt available in DeclarativePipelineTest only BasePipelineTest. how do I access it?

**Comment by red8888** [comment]
loadScript() just load it before executing I think it does the same thing right?

**Comment by red8888** [comment]
Im closing this, this is working for me- unfortunately I can't remember how I fixed it

**Comment by psimms-r7** [comment]
> def script = runScript("vars/Jenkinsfile")

Do you have a copy of code that works? I am experiencing similar issues
