### ISSUE TITLE
Assertion on withEnv fails when Env Var value contains equals (=) sign

### ISSUE THREAD

**Issue by stefano-m** [jenkinsci/JenkinsPipelineUnit#388]
Hello, and thank you for working on JenkinsPipelineUnit.

When environment variables containing *equals* signs in their **values** are used in `withEnv`, the BasePipelineTest check fails erroneously because it splits the variable "too much".

A use case is [passing tags or other parameters to the AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/dynamodb/create-table.html#examples):

``` groovy
withEnv([
'TAGS=Key=Owner,Value=blueTeam',
'ATTR_DEFS=AttributeName=Artist,AttributeType=S AttributeName=SongTitle,AttributeType=S',
'KEY_SCHEMA=AttributeName=Artist,KeyType=HASH AttributeName=SongTitle,KeyType=RANGE',
'THROUGHPUT=ReadCapacityUnits=5,WriteCapacityUnits=5'
]) {
    sh '''
      aws dynamodb create-table \
    --table-name MusicCollection \
    --attribute-definitions $ATTR_DEFS \
    --key-schema $KEY_SCHEMA \
    --provisioned-throughput $THROUGHPUT \
    --tags $TAGS
       '''
}
```

However, the above causes an assertion failure in the BasePipelineTest because the code uses `item.split('=')` which splits along **all** `=` resulting in an array of more than 2 elements. Unfortunately, this is breaking some tests on pipelines that otherwise work fine.

https://github.com/jenkinsci/JenkinsPipelineUnit/blob/075a7b2bb7662b56a2cde92d340d96e66a98b7be/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L249-L250

IIUC something like

``` groovy
def item = it.split('=', 2)
```

should do the correct thing and split along the first `=` only.

Thank you.

**Comment by stefano-m** [comment]
At the moment this is working for me:

``` groovy
      helper.registerAllowedMethod(
            'withEnv',          // see https://github.com/jenkinsci/JenkinsPipelineUnit/issues/388
            [List, Closure],
            { List list, Closure c ->
                def stashedEnv = [:]
                try {
                    stashedEnv.putAll(binding.getVariable('env') as Map)
                } catch (MissingPropertyException e) {
                    // 'env' not set yet?
                }

                list.each {
                    def item = it.split('=', 2)
                    assert item.size() == 2, "Variable ${it} in withEnv (${list}) cannot be split in NAME/VALUE pair"
                    addEnvVar(item[0], item[1])
                }

                try {
                    c.delegate = binding
                    helper.callClosure(c)
                } finally {
                    // Restore original contents of 'env'
                    binding.setVariable('env', stashedEnv)
                }
            }
        )
```

**Comment by juanpablo-santos** [comment]
Another usual use-case that's also hit by this bug is when setting a custom `MAVEN_OPTS` using `withEnv`:

```
withEnv( [ 'MAVEN_OPTS=-Djansi.force=true' ] ) {
...
```

suggested patch works, but that forces us to overwrite the complete `registerAllowedMethods()` with the aforementioned change to avoid the exception thrown otherwise, which is unfortunate.
