### ISSUE TITLE
global var Setting

### ISSUE THREAD

**Issue by waytoharish** [jenkinsci/JenkinsPipelineUnit#402]
Hi Team,
I am trying to write a Test where i have Script1-> Script2(is also using the env variable)
I tried to set the variable like-
 def test_env = [:]
    test_env.put("ENABLE_CRED_SCAN","Test")
    test_env.put("BRANCH_NAME","master")
    test_env.put("COMMIT_HASH","test")
    test_env.put("CREDSCAN_ENDPOINT","test")
    
    These variable is accessible in Script1 but getting 
    
    No such property: env for class: com.jenkins.library.Utils
    
    Please could someone help me here

**Comment by MichaelJKar** [comment]
Hi all,

I have a similar/the same problem. Whenever I try to access params in Groovy classes located in the src/main folder of a shared lib, I get the error mentioned by @waytoharish 

For example, when executing this line in a class `Maven.groovy`:  
```
sh (label: 'Build maven', script: "mvn ${MAVEN_CONFIG} install -Dmaven.test.skip=true ${MAVEN_ARGS}")`
```
, I get the following error: 
```
groovy.lang.MissingPropertyException: No such property: MAVEN_CONFIG for class: de.karstadt.jenkinsPipelineLib.Maven
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:310)
	at de.karstadt.jenkinsPipelineLib.Maven.build(Maven.groovy:5)
```

Thus, the global params-variable `MAVEN_CONFIG` seems to be unavailable in the shared lib class. Accessing the variable via `params.MAVEN_CONFIG` yields the same result. Interestingly, environment variables seem to be accessible.

Thanks in advance for your help.

**Comment by nre-ableton** [comment]
Yes, using `params` or `env` is necessary for this. Jenkins creates these bindings at runtime, but it's not really possible/feasible for us to do the same with JenkinsPipelineUnit.

I would also say that It's more pedantically correct (and thus recommended) to use `params.XYZ` in a pipeline, since that makes it more obvious to the reader that the given variable comes from the environment or job parameters, as the case may be.

As such, I'm closing this issue as "wontfix". Please feel free to reopen if you strongly disagree with my decision. :slightly_smiling_face:

**Comment by MichaelJKar** [comment]
Thanks, @nre-ableton. I can understand the decision to not support direct access to parameters, if this is technically difficult. However, even accessing via `params` does not work in my case. 

Example:
When replacing the line in question with
```
sh (label: 'Build maven', script: "mvn ${params.MAVEN_CONFIG} install -Dmaven.test.skip=true ${params.MAVEN_ARGS}")`
```
the error changes to 
```
groovy.lang.MissingPropertyException: No such property: params for class: de.karstadt.jenkinsPipelineLib.Maven
```

Interestingly, access to the `env` map is possible at the same point. Only `params` is not accessible. Also, access to the `params` map is also possible for scripts in the vars directory. I just does not work in "real" Groovy classes in the src directory.
