### ISSUE TITLE
DockerMock calls don't show up in the call stack

### ISSUE THREAD

**Issue by figaw** [jenkinsci/JenkinsPipelineUnit#406]
### Feature Request

Most of the time when we write unit tests, we're verifying the callStack like in the examples:

```groovy
@Test
void should_execute_without_errors() throws Exception {
    runScript("Jenkinsfile")
    assertThat(helper.callStack.findAll { call ->
        call.methodName == "sh"
    }.any { call ->
        callArgsToString(call).contains("mvn verify")
    }).isTrue()
    assertJobStatusSuccess()
}
```

But when we use the `docker-workflow-plugin` all the calls to e.g. `docker.image` or `docker.build` aren't added,
when we add a binding like `binding.setVariable('docker', new DockerMock())`.

One way to fix this, is to modify the call-stack like in `PipelineTestHelper.groovy`, but I don't know if that's an inelegant solution, and it's easier to do in another way?

I've included an example below of what it would look like for e.g. the `image`-method:

```groovy
package com.lesfurets.jenkins.unit

@SuppressWarnings(['EmptyMethod', 'MethodReturnTypeRequired', 'UnusedMethodParameter'])
class DockerMock implements Serializable {

    PipelineTestHelper helper
    Object script

    DockerMock(script = null, helper = null){
        this.script = script
        this.helper = helper
    }

    ...

    Image image(String id) {
        if (script != null && helper != null){
            int depth = Thread.currentThread().stackTrace.findAll { it.className == delegate.class.name }.size()
            helper.registerMethodCall(script, depth, "docker.image", id)
        }
        return new Image(id)
    }
}
```

The null-checks are there so it can be used along with just `DockerMock()`.

The test script has access to the `helper` since it runs `helper.callStack.findAll..`. But it will need access to the `script` with a 
```groovy
script = loadScript("Jenkinsfile")
```
And not just `runScript("Jenkinsfile")` like in the example. But an example could be provided for that. Usage is then like,

```groovy
script = loadScript("Jenkinsfile")
binding.setVariable('docker', new DockerMock(script, helper))
```

--- 

Currently we have our own `ExtendedDockerMock.groovy` inspired by <https://github.com/jenkinsci/JenkinsPipelineUnit/issues/362#issuecomment-859482509> which looks like..

```groovy
import com.lesfurets.jenkins.unit.DockerMock
import com.lesfurets.jenkins.unit.PipelineTestHelper

@SuppressWarnings(['EmptyMethod', 'MethodReturnTypeRequired', 'UnusedMethodParameter'])
class ExtendedDockerMock extends DockerMock {

    PipelineTestHelper helper
    Object script

    ExtendedDockerMock(script, helper){
        super()
        this.script = script
        this.helper = helper
    }

    Image image(String id) {
        Image image = super.image(id)

        int depth = Thread.currentThread().stackTrace.findAll { it.className == delegate.class.name }.size()
        helper.registerMethodCall(script, depth, "docker.image", id)

        return image
    }

}
```

But ideally we'd just get a solution in `DockerMock`.

The entire thing is a bit reverse-engineered from the `PipelineTestHelper`. But before spending a lot of time creating a PR, I'd like to know if this is something you want? Another alternative is the one mentioned in https://github.com/jenkinsci/JenkinsPipelineUnit/issues/362. it doesn't require the `script` or `helper` but you have to inspect the `DockerMock` directly.

**Comment by figaw** [comment]
I've noticed that `BasePipelineTest.groovy` makes a `binding.setVariable('docker', new DockerMock())` and that it has access to the `helper`, but I'm not entirely sure how it would access the `script` which.. should be the context of the method call, in 
```
        helper.registerMethodCall(script, depth, "docker.image", id) // from the example above
```
 🤔 
.. But if `BasePipelineTest` could make the binding, then the users wouldn't even have to change `DockerMock()` to `DockerMock(script, helper)`.

**Comment by nre-ableton** [comment]
@figaw I think that your plan sounds good in principle. The only thing is, I'm not sure where the script context would come from in `BasePipelineTest` itself when it tries to create the `DockerMock` object. Where would this come from?

**Comment by figaw** [comment]
So I guess, if you "don't need" the stack trace, we could keep `binding.setVariable('docker', new DockerMock())` in the `BasePipelineTest.groovy`. And then, if you need the stack trace, you can manually overwrite it in your testfile, with 
`binding.setVariable('docker', new DockerMock(script, helper))`. It just feels a bit unclean.

Is there a better way to do this by rewriting some of the `PipelineTestHelper` maybe? I have to admit that some of the things going on in that class are a bit magic and sophisticated.
