### ISSUE TITLE
How can i mock methods of mocked jenkins variables

### ISSUE THREAD

**Issue by g3n35i5** [jenkinsci/JenkinsPipelineUnit#413]
I have a mocked `currentBuild` variable in my test, set up according to the [the documentation](https://github.com/jenkinsci/JenkinsPipelineUnit#mock-jenkins-variables).

Now, i have a method in my shared library that aborts all currently running builds of a job if there is a newer build:

```java
@NonCPS
void abortPreviousBuilds() {
    Run previousBuild = this.script.currentBuild.rawBuild.getPreviousBuildInProgress()
    // And so on
}
```

How can i mock the `getPreviousBuildInProgress` method of the previous build?

What I've tried so far:

```java
this.binding.getVariable('currentBuild').rawBuild = [:]
this.binding.getVariable('currentBuild').rawBuild.previousBuild = [
    result: 'UNSTABLE',
    getPreviousBuildInProgress: () -> {return null}
]
```

or

```java
this.binding.getVariable('currentBuild').rawBuild = [:]
this.binding.getVariable('currentBuild').rawBuild.previousBuild = [
    result: 'UNSTABLE',
    'getPreviousBuildInProgress()': () -> {return null}
]
```

but I'm getting the following error in any case

```
No signature of method: java.util.LinkedHashMap.getPreviousBuildInProgress() is applicable for argument types: () values: []
```

Is this the way to go if i want to skip this method in my unit tests? And if so, what do I need to change in order to get my code running?

**Comment by g3n35i5** [comment]
@nre-ableton  So far I haven't had any problems in productive use, I like the imports very much to be able to be sure to really call the right methods, etc. and not have any name clashes.

Well, the issue is closed thanks to your help, thanks a lot! Maybe one more question: You seem to be dealing with the topic of unit testing of Jenkins pipelines/shared libraries for quite some time, do you have any tips for further sources/courses/etc. that can help to really get to grips with the topic? Maybe there are even coaches or freelancers somewhere who do this?

**Comment by nre-ableton** [comment]
> @nre-ableton So far I haven't had any problems in productive use, I like the imports very much to be able to be sure to really call the right methods, etc. and not have any name clashes.

Whatever approach works best for you. :+1: 

> Well, the issue is closed thanks to your help, thanks a lot! Maybe one more question: You seem to be dealing with the topic of unit testing of Jenkins pipelines/shared libraries for quite some time, do you have any tips for further sources/courses/etc. that can help to really get to grips with the topic? Maybe there are even coaches or freelancers somewhere who do this?

The only advice that I find myself routinely giving on this project is to move the bulk of the pipeline library logic out of singletons and into classes (for example, see [this comment](https://github.com/jenkinsci/JenkinsPipelineUnit/issues/308#issuecomment-707078194)). That makes pipeline libraries much easier to test (and I suspect from your code snippets that you are already doing this). Otherwise I tend to think that following best-practices for Java unit testing is generally the way to go.
