### ISSUE TITLE
Mock `library` that takes map args

### ISSUE THREAD

**Issue by dblock** [jenkinsci/JenkinsPipelineUnit#418]
In https://github.com/opensearch-project/opensearch-build/pull/924 I am loading a library via local (`legacySCM`) SCM.

```
lib = library(identifier: "jenkins@current", retriever: legacySCM(scm))
``` 

I needed to stub `scm`, `legacySCM` and `library`.

```groovy
        binding.setVariable('scm', {})
        helper.registerAllowedMethod("legacySCM", [Closure.class], null)
        
        helper.registerAllowedMethod("library", [Map.class], { Map args ->
            helper.getLibLoader().loadLibrary(args["identifier"])
            return new LibClassLoader(helper, null)
        })
```

Does this belong in the library? We probably need to do more and pass SCM through? What's the right way to do this?

**Comment by nre-ableton** [comment]
Yeah, I think that using `library` with mapped arguments is perhaps not as common as using either the `@Library` annotation or just calling it with a string. Anyways, I opened #422 to fix this. Please have a look @dblock; if it seems ok to you, I'll go ahead and merge it.
