### ISSUE TITLE
Release v. Next please

### ISSUE THREAD

**Issue by dblock** [jenkinsci/JenkinsPipelineUnit#430]
### Dependencies

Hoping to get a release with https://github.com/jenkinsci/JenkinsPipelineUnit/pull/421 fixed so I can use it in https://github.com/opensearch-project/opensearch-build.

### Feature Request

Release v. Next please. Also no stress and thank you. If someone else is waiting for a release for something specific add it here or 👍  for signal.

**Comment by nre-ableton** [comment]
I would like to get https://github.com/jenkinsci/JenkinsPipelineUnit/pull/429 merged before making a release, otherwise I agree, we should make one soon.

**Comment by dblock** [comment]
> I would like to get #429 merged before making a release, otherwise I agree, we should make one soon.

Sounds like feature creep to me ;) jk

**Comment by nre-ableton** [comment]
https://github.com/jenkinsci/JenkinsPipelineUnit/releases/tag/v1.12
