### ISSUE TITLE
String in Exception for failed shell-step has different format than the Jenkins shell-step plugin 

### ISSUE THREAD

**Issue by figaw** [jenkinsci/JenkinsPipelineUnit#455]
Sometimes we run cli's that fail with specific error codes, so we match against these with e.g. some

```groovy
try { 
  // do stuff
} catch(e) { 
  if (e.getMessage().equals("...")) { 
    // handle error
  } 
}
``` 

But the messages differ when we run the tests and the actual pipelines on Jenkins.

---

From what I can see the problem stems from this:

https://github.com/jenkinsci/JenkinsPipelineUnit/blob/659f4f06498e58f9698ebd01defbdd69cb85f4d1/src/main/groovy/com/lesfurets/jenkins/unit/PipelineTestHelper.groovy#L741

The formats in the `workflow-durable-task-step-plugin`:

https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java#L660
```groovy
listener().getLogger().println("script returned exit code " + exitCode);
```

and https://github.com/jenkinsci/workflow-durable-task-step-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java#L663

```groovy
getContext().onFailure(new AbortException("script returned exit code " + exitCode));
```

---

This means we have to write our business logic so it both matches `"Script returned exit code: " + exitValue` and `"script returned exit code " + exitCode`, which means we're 

1. patching our business logic to fit the test-framework, (you should write testable code, but it _should_ be framework agnostic?) And
2. not really testing the `"script returned exit code " + exitCode`-error message

My suggestion is to align the `PipelineTestHelper.groovy` with the `"script returned exit code " + exitCode` format.

**Comment by nre-ableton** [comment]
So philosophically speaking, I don't really care what the exception message of the script mocks return, but IMHO it's a bit of a code smell to examine exception messages in the manner that you are doing in order to catch specific cases. Why not catch the proper exception class instead?

In other words...

```groovy
try {
  sh('blah')
} catch (hudson.AbortException e) {
  // do stuff
}
```

...or if you don't want your code to depend on that specific symbol:

```groovy
try {
  sh('blah')
} catch (e) {
  if (e.class.name == 'hudson.AbortException') {
    // do stuff
  }
}
```

Or am I missing something?

**Comment by figaw** [comment]
I completely agree, the reason we have to do it in the first place, is because we're wrapping clis in shell steps, and they don't throw nice exceptions; they just fail with the `AbortException` (I guess?), and then we have to figure out what went wrong.

So to read the specific error code, I'd still have to use 
```
try {
  sh('blah')
} catch (e) {
  if (e.class.name == 'hudson.AbortException') {
    if ( e.getMessage().contains('1') ) {
      // handle exitcode 1
    } else if ( e.getMessage().contains('254') ) {
      // handle 254
    }
  }
}
```

So I thought it was just simpler to check for equality in the first place. 

(This can also get into weird cases where exitcodes "containing 10 or 100" will trigger the `contains('1')`. So it gets even more complicated to match for "error strings that end with a 1" with something like `e.getMessage() ==~ /.* 1$/`)

**Comment by nre-ableton** [comment]
@figaw In that case, why not use `returnStatus` and then examine the script's exit code? In other words:

```groovy
int status = sh(script: 'blah', returnStatus: true)
if (status != 0) {
  // handle exit code
}
```

**Comment by figaw** [comment]
Honestly I'd love to, but unfortunately we need the stdout from the `sh`-step, and Jenkins doesn't support having `returnStatus: true, returnStdout: true` at the same time (which is a "feature" the community has broadly requested for ages, but has been "politely declined as useless." It's a whole thing.)

But building on your original suggestion, it would probably make sense to also change the exception type, so you could catch the `hudson.AbortException` as well. So we could do..

```
def data;
try { // `aws secretsmanager get-secret-value` fails if the secret doesn't exist
    data = sh(script: "3rd-party-cli ...", returnStdout: true)
} catch (e){
    if(e.getMessage().contains("123")){
        echo "not actually an error, but the cli didn't succeed with the action"
    } else {
        // something actually went wrong
        throw e
    }
}
```

But at the same time, it would be nice if the messages were aligned, when we're trying to figure out the specific status code. Imagine the collision between "1, 10, 100" if you don't check them in the right order..

**Comment by nre-ableton** [comment]
@figaw I see. Yeah, that's a tough situation. Well, at the end of the day, I guess the actual exception message produced by the `sh` mock isn't really that big of a deal, even though it feels a bit dirty to compare messages in this manner. I made a PR to fix the message format, though. I'll merge it once it passes CI.
