### ISSUE TITLE
v1.14 release

### ISSUE THREAD

**Issue by UlrichEckhardt** [jenkinsci/JenkinsPipelineUnit#493]
### What feature do you want to see added?

Actually, none but those already present in the master branch. ;) Can we get a release? Do you need anything for it?

**Comment by nre-ableton** [comment]
Sure, I can make a release.

**Comment by nre-ableton** [comment]
https://github.com/jenkinsci/JenkinsPipelineUnit/releases/tag/v1.14 is out, and the artifacts appear to be available at https://repo.jenkins-ci.org/artifactory/releases/com/lesfurets/jenkins-pipeline-unit/1.14/. Thanks also for your contributions to this release @UlrichEckhardt. :+1:
