### ISSUE TITLE
Stub and verify script on vars that import class from src and pass steps

### ISSUE THREAD

**Issue by fadeltd** [jenkinsci/JenkinsPipelineUnit#512]
### Describe your use-case which is not covered by existing documentation.

I have this problem when testing a shared library that my team is working on.
So I have private jenkins and working on scripts that can be reused by others (through shared library).
This is my project directory
```sh
.
├── build.gradle
├── src
│   └── org
│       └── example
│           └── Downloader.groovy
├── test
│   └── groovy
│       └── DownloaderTest.groovy
└── vars
    └── download.groovy
```

I have this class that call API with `sh` curl

```groovy
// src/org/example/Downloader.groovy
package org.example

class Downloader implements Serializable {

    private String token
    private String baseUrl
    private def steps

    Downloader(steps, String token, String baseUrl) {
        this.steps = steps
        this.baseUrl = baseUrl
        this.token = token
    }

    private getProject(String projectId) {
        String curl = getCurl("projects/${projectId}")
        String response = steps.sh(label: "Get item from id", script: curl, returnStdout: true)
        def item = new groovy.json.JsonSlurperClassic().parseText(response)
        return item.first()
    }

    private void downloadItem(String itemId, String path) {
        steps.sh(
            label: "Download ${path} from item ${itemId}",
            script: getCurl("item/${itemId}/raw/${path}", '--location -O')
        )
    }

    private String getCurl(String path, String extra = "") {
        return "curl ${extra} -s --header 'Authorization: Bearer ${this.token}' '${this.baseUrl}/${path}'"
    }

    public void download(String projectId, String path) {
        String itemId = getItem(projectId)?.id
        downloadItem(itemId, path)
    }
}

```

Then this is my vars that can be accessed with `@Library('lib-downloader')`

```groovy
// vars/download.groovy
import org.example.Downloader

def call(
    String projectId, String path, String token = env.TOKEN, String baseUrl = env.BASE_URL
) {
    new Downloader(this, token, baseUrl).download(projectId, path)
    sh script:'ls', returnStdout: true
}
```

and this is my test class
```groovy
// test/groovy/DownloaderTest.groovy
import com.lesfurets.jenkins.unit.BasePipelineTest
import org.junit.Before
import org.junit.Test

class DownloaderTest extends BasePipelineTest {

    @Before
    @Override
    void setUp() throws Exception {
        scriptRoots += 'vars'
        super.setUp()
    }

    @Test
    void testDownload() {
        def token = 'token'
        def url = 'https://example.com/api/v2'
        def projectId = '125'
        def path = 'build/reports_04062022.csv'
        List expectedShellData = [
            [
                call: "curl -s --header 'Authorization: Bearer ${token}' '${url}projects/${projectId}'",
                result: '[{ "id": 14409989, "item_name": "Report April 6 2022", "status": "success"}]',
            ],
            [
                call: "curl --location -O -s --header 'Authorization: Bearer ${token}' '${url}item/14409989/raw/${path}'",
                result: '',
            ],
        ]

        def script = loadScript('vars/download.groovy')
        expectedShellData.each { Map expectedData ->
            helper.addShMock(expectedData.call, expectedData.result, 0)
        }
        script.call(projectId, path, token, url)

        printCallStack()
        assertJobStatusSuccess()
    }
}

```

what I need to do is to stub and verify that the `steps.sh` curl is called with the expected parameters and returns the mocked JSON, but every time I test this, it always fails because the `sh(script: curl, returnStdout: true)` returns null.

```
> Task :test

DownloaderTest > testDownload FAILED
    java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty.
```

Also this is my `build.gradle`

```gradle
plugins {
    id 'groovy'
    id 'jacoco'
}

group = 'org.example'
version = '0.0.1'

repositories {
    mavenCentral()
    maven { url = uri('https://repo.jenkins-ci.org/releases/') }
}

dependencies {
    implementation 'org.codehaus.groovy:groovy-all:3.0.10'
    testImplementation 'com.lesfurets:jenkins-pipeline-unit:1.14'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:4.4.0'
}

sourceSets {
    test {
        groovy.srcDirs 'test/groovy'
    }
    main {
        groovy.srcDir 'src'
    }
}

import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.api.tasks.testing.logging.TestLogEvent

test {
    dependsOn 'cleanTest'
    testLogging {
        // set options for log level LIFECYCLE
        events TestLogEvent.FAILED,
               TestLogEvent.PASSED,
               TestLogEvent.SKIPPED,
               TestLogEvent.STANDARD_OUT
        exceptionFormat TestExceptionFormat.FULL
        showExceptions true
        showCauses true
        showStackTraces true

        // set options for log level DEBUG and INFO
        debug {
            events TestLogEvent.STARTED,
                   TestLogEvent.FAILED,
                   TestLogEvent.PASSED,
                   TestLogEvent.SKIPPED,
                   TestLogEvent.STANDARD_ERROR,
                   TestLogEvent.STANDARD_OUT
            exceptionFormat TestExceptionFormat.FULL
        }
        info.events = debug.events
        info.exceptionFormat = debug.exceptionFormat

        afterSuite { desc, result ->
            if (!desc.parent) { // will match the outermost suite
                def output = "Results: ${result.resultType} (${result.testCount} tests, ${result.successfulTestCount} passed, ${result.failedTestCount} failed, ${result.skippedTestCount} skipped)"
                def startItem = '|  ', endItem = '  |'
                def repeatLength = startItem.length() + output.length() + endItem.length()
                println('\n' + ('-' * repeatLength) + '\n' + startItem + output + endItem + '\n' + ('-' * repeatLength))
            }
        }
    }
}
```
How can I stub and test this? Do I need to add other dependencies?

**Comment by fadeltd** [comment]
Hi @nre-ableton thanks for replying!

I made a mistake about the script I'm attaching, it should be `0..expectedCalls.size - 1`

I'm aware that `JsonSlurperClassic().parseText` can't receive an empty string, and that's why the `sh curl --location -O` doesn't have `JsonSlurperClassic`.
The issue I'm having is `helper.addShMock` didn't work as I expected.
The sh call from `steps.sh` with `returnStdout: true` doesn't return the mock value that I have assigned.

I have tried your script, and it still has the same issue.
This line still returns empty string instead of the mocked return value `steps.sh(label: "Get item from id", script: curl, returnStdout: true)`

**Comment by fadeltd** [comment]
Ah I see, thanks, I've fixed the description on the issue so it will be easier to debug.

I've also tried passing the base url (without the env), yet still encountered the same problem

```groovy
def url = 'https://example.com/api/'
...
script.call(projectId, path, token, url)
```

`steps.sh` with curl still empty string.
Is it really the correct way to use `helper.addShMock` to mock `steps.sh`/`script.sh` in a `src/package/class` imported by script in `vars`?
I've been looking for the docs/example for this, and none of it seems to use the same approach. Most that I've seen works use `sh` inside the `vars` script, without the `src/package/class`

**Comment by nre-ableton** [comment]
@fadeltd Thanks for updating the sample code. I got your test to work. The problem is caused by several typos and small mistakes -- please remember that the script needs to match *exactly*. As of https://github.com/jenkinsci/JenkinsPipelineUnit/pull/498, script patterns can also be registered as `sh` mocks, but that change hasn't been released yet.

Anyways, here is the diff between your code above (in red) and my working version (in green):

```diff
-call: "curl -s --header 'Authorization: Bearer ${token}' '${url}projectId/${projectId}'",
+call: "curl  -s --header \"Authorization: Bearer ${token}\" \"${url}/projects/${projectId}\"",
```

So take careful note of the following:

1. An extra space after `curl`. This is because your `getCurl` method takes an `extra` parameter, but it's empty, so there will be two spaces after `curl`.
2. Double quotes vs. single quotes
3. A trailing slash after `url`
4. A typo, `projectId` vs `projects`

How I figured this out was to place a breakpoint in `getProject` on the line directly after `String response = script.sh(...)`. Then I looked at the values in the debugger for `curl` compared to `this.helper.mockShOutputs`, which is actually part of `GitHubTest`, so it's in the stack a few frames above:

![Screenshot from 2022-04-12 11-44-21](https://user-images.githubusercontent.com/16208985/162931617-dce5a12c-e469-4524-a2b6-5e05081dec44.png)

In regards to your question, yes, I believe that your approach of mocking `sh` in a class imported by `vars` is the way to go. It's typically much better than putting all the business logic in `vars` singletons.

**Comment by UlrichEckhardt** [comment]
Just as a heads-up, either of the two (double or single quotes) leaves you vulnerable to injections: https://stackoverflow.com/questions/71589652/how-to-avoid-code-injection-in-jenkins-shell-calls.

**Comment by fadeltd** [comment]
@nre-ableton Oh yeah and 1 more thing that I'm curious about.

If I want to test the class directly and pass the `steps`/`script` via constructor, like for this example I have `Downloader(steps)`, what should I pass?
From the `vars` I can instantiate the object with `Download(this)`.

So, instead of calling it from `vars` like this
```groovy
def script = loadScript('vars/download.groovy')
script.call(...)
````

What should I pass?
```groovy
import com.lesfurets.jenkins.unit.BasePipelineTest
import org.junit.Before
import org.junit.Test
import org.example.Downloader

class DownloaderTest extends BasePipelineTest {
    // ...
    @Test
    void testDownload(){
        // ...
        new Downloader(...)
    }
}
```

Because passing `this` will cause missing `sh` method.

I think this problem is pretty similar to this comment https://github.com/jenkinsci/JenkinsPipelineUnit/issues/93#issuecomment-571956111
