### ISSUE TITLE
Can "params" be defined as a java.util.Collections$UnmodifiableMap instead of a regular map?

### ISSUE THREAD

**Issue by red8888** [jenkinsci/JenkinsPipelineUnit#528]
### What feature do you want to see added?

Maybe I'm using it wrong but in an actual pipeline run the "params" variable is an java.util.Collections$UnmodifiableMap. When running the unit test pipeline framework it appears to be a regular map.

Maybe what I'm asking for is impossible. Got an exception because I tried to treat params like a Map when it is not. Ran locally without errors, but failed on actual Jenkins.

Thanks!

**Comment by nre-ableton** [comment]
That's a good point, but unfortunately this isn't a trivial fix because internally, we _do_ need to modify the map in order to add parameters to it from calls made to `addParam`. So we need to think about a better solution.
