### ISSUE TITLE
DockerMock image build should accept multiple strings args

### ISSUE THREAD

**Issue by stanovchar** [jenkinsci/JenkinsPipelineUnit#533]
### What feature do you want to see added?

Currently `docker.build` mock is setup to accept two strings arguments
```
docker.build('my-awesome-image', '--build_arg arg1=val1 --build_arg arg2=val2')
```

However real `docker.build` can process multiple string arguments
```
docker.build('my-awesome-image', '--build_arg arg1=val1', '--build_arg arg2=val2')
```

**Comment by stchar** [comment]
I was mine wrong assumption.
 
docker-workflow-plugin doesn't support the signature bellow
```
docker.build('my-awesome-image', '--build_arg arg1=val1', '--build_arg arg2=val2')
```
Canceling the issue.
