### ISSUE TITLE
mock for build step

### ISSUE THREAD

**Issue by wityamin** [jenkinsci/JenkinsPipelineUnit#551]
### What feature do you want to see added?

addBuildMock functionality to check pipeline behavior for build step.

### Upstream changes

https://www.jenkins.io/doc/pipeline/steps/pipeline-build-step/#build-build-a-job 
-----------------------------------------------------------------------------------------
propagate : boolean (optional)

If enabled (default state), then the result of this step is that of the downstream build (e.g., success, unstable, failure, not built, or aborted). If disabled, then this step succeeds even if the downstream build is unstable, failed, etc.; use the result property of the return value as needed.

**Comment by nre-ableton** [comment]
This is already implemented in `BasePipelineTest`: https://github.com/jenkinsci/JenkinsPipelineUnit/blob/b737e00e91ec4a69bf5ed18b4dd2265b9d48c457/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L134-L141

Does that mock not work for you?

**Comment by prudhvigodithi** [comment]
Hey @nre-ableton looks like same issue with me. I'm not able to mock the following build job (parameters) logic 

Following is my code in jenkinsfile
```
build job: 'distribution-promote-artifacts', wait: true, parameters: [choice(name: 'DISTRIBUTION_JOB_NAME', value: 'distribution-build-opensearch-dashboards'), 
                                                                    choice(name: 'DISTRIBUTION_PLATFORM', value: 'linux'),
                                                                    choice(name: 'DISTRIBUTION_NAME', value: 'tar'),
                                                                    choice(name: 'DISTRIBUTION_ARCHITECTURE', value: 'x64'),
                                                                    string(name: 'DISTRIBUTION_BUILD_NUMBER', value: params.OPENSEARCH_DASHBOARDS_RC),
                                                                    string(name: 'INPUT_MANIFEST', value: "${params.RELEASE_VERSION}/opensearch-dashboards-${params.RELEASE_VERSION}.yml"),
                                                                ]
                                                                                ]
```

When is execute `super.testPipeline('jenkinsfile')`, notice the `release-promotion.build()` method returns `null` for `parameters`, but the jenkins when executed it is able to trigger the job with right parameters only when testing it returns `null` for the parameters.

```
release-promotion.echo(Triggering distribution-promote-artifacts for opensearch windows)
release-promotion.choice({name=DISTRIBUTION_JOB_NAME, value=distribution-build-opensearch-dashboards})
release-promotion.choice({name=DISTRIBUTION_PLATFORM, value= linux})
release-promotion.choice({name=DISTRIBUTION_NAME, value=tar})
release-promotion.choice({name=DISTRIBUTION_ARCHITECTURE, value=x64})
release-promotion.string({name=DISTRIBUTION_BUILD_NUMBER, value=3050})
release-promotion.string({name=INPUT_MANIFEST, value=1.0.0/opensearch-dashboards-1.0.0.yml})
release-promotion.build({job=distribution-promote-artifacts, wait=true, parameters=[null, null, null, null, null, null]})
```

Please let me know if this is not related, I can open a new issue.

**Comment by nre-ableton** [comment]
@prudhvigodithi Yes, please open a new issue. You can just copy your above comment to it.
