### ISSUE TITLE
document addParam

### ISSUE THREAD

**Issue by jcrben** [jenkinsci/JenkinsPipelineUnit#588]
### Describe your use-case which is not covered by existing documentation.

In release 1.15 params became immutable but the documentation doesn't seem to mention that. Some tips on using it would also be helpful.

I started messing around with addParam - it takes an Object for the value but for some reason I'm having trouble getting it to take a String? (New to Java/Groovy so I'm probably missing something totally obvious.) I keep getting messages like `groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.PipelineTestHelper.addParam() is applicable for argument types: (java.lang.String, java.lang.String, java.lang.Boolean) ` despite casting the String to java: 

```
Object someValue = new String("hmm")
println("someValue" + ((Object) someValue).getClass())
helper.addParam('GitRepo', (Object) someValue, true)
```

I'm using the active-choice plugin and most of my parameters are strings.

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

https://github.com/jenkinsci/JenkinsPipelineUnit/releases/tag/v1.15

https://github.com/jenkinsci/JenkinsPipelineUnit/blob/17f78601c56dcb7babb2a24a94d4ac55ff3c1468/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L527-L535

**Comment by nre-ableton** [comment]
You should be able to just do:

```groovy
addParam('GitRepo', 'someValue')
```

(Note the lack of `helper.`, since `addParam` is a method provided by `BasePipelineTest`). I just verified that this code works:

```groovy
class FooTest extends BasePipelineTest {
  Object script = null

  @Override
  @BeforeEach
  void setUp() {
    super.setUp()
    addParam("foo", "bar")
  }

  @Test
  void foo() {
    assertEquals("bar", getBinding().getVariable('params')['foo'])
  }
```

That said, I agree that `addParam` could use some better documentation, so I'll submit a PR to improve that a bit.
