### ISSUE TITLE
Is it possible to run unit tests over a Jenkinsfile in a remote git repo?

### ISSUE THREAD

**Issue by Lemming3842** [jenkinsci/JenkinsPipelineUnit#602]
### What feature do you want to see added?

Currently we have our main project with a multibranch pipeline within a different git repository of where we are running the jenkinspipelineunit tests. And in order to avoid duplicating all Jenkinsfiles into the gradle project, I was wondering if there is any way to get the Jenkinsfile from that remote git reposittory and use it for the _runScript_ command. Cloning the whole repo temporarily into the gradle project could be an option but I am not sure if there is a better way.

I didn't see it documented but might have overlooked it. I saw on how to get shared libraries from remote, but not the jenkinsfile itself. Could it be possible?

**Comment by nre-ableton** [comment]
> I was wondering if there is any way to get the Jenkinsfile from that remote git reposittory and use it for the _runScript_ command...

If your repository is on GitHub, you can use the API to fetch a single file directly. Here's some (adapted) Groovy code that does that:

```groovy
static final String GITHUB_API_VERSION = '2022-11-28'

String fetchGitHubFile(String repoSlug, String filename, String commit) {
  String result = null
  withCredentials([string(credentialsId: 'your-github-api-key', variable: 'GITHUB_TOKEN')]) {
    String jenkinsfileUrl = "https://api.github.com/repos/${repoSlug}/contents/${filename}?ref=${commit}"
    List customHeaders = [
      [name: 'Accept', value: 'application/vnd.github.v3.raw'],
      [name: 'Authorization', value: 'token ' + GITHUB_TOKEN, maskValue: true],
      [name: 'X-GitHub-Api-Version', value: GITHUB_API_VERSION]
    ]

    try {
        result = httpRequest(customHeaders: customHeaders, url: jenkinsfileUrl).content
      }
    } catch (Exception e) {
      echo "Failed to fetch '${filename}'"
    }
  }
  return result
}
```

So the above above function could be called like:

```groovy
String jenkinsfile = fetchGitHubFile('jenkinsci/JenkinsPipelineUnit', 'Jenkinsfile', '718e1d1a52312d21a439434ae9354b3e97d2d69e')
```

**Comment by Lemming3842** [comment]
Thank you very much for your answer!! I'll definitely will try like that, seems like i could work it out with this.

**Comment by nre-ableton** [comment]
@Lemming3842 no problem! Let us know if it works so we can close the issue. Best of luck.

**Comment by Lemming3842** [comment]
Sorry for the delay answering, but after several tries, I didnt managed it to work. the thing is that it does not accept the withCredentials as valid method, if im reading the groovy output correctly. here is an example of my code in case you can give me any insight, ths version is a modification of yours after several trial and error, let me know if you see anything weird, but i cannot manage to make it through the withCredentials. Not sure if I should make the function as a library and import it:

```import com.lesfurets.jenkins.unit.declarative.*
import static com.lesfurets.jenkins.unit.global.lib.LibraryConfiguration.library
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test


class TestPrueba extends DeclarativePipelineTest {

    @Override
    @BeforeEach
    void setUp() throws Exception {
        super.setUp()
        String jenkinsfile = fetchGitHubFile('repo/test', 'Jenkinsfile', 'master')
        File file = new File("jenkinsfiletest").createNewFile() << jenkinsfile
    }

    @Test
    void executeWithoutErrors() {
        runScript('Jenkinsfile')
        assertJobStatusSuccess()
        printCallStack()
    }

    String fetchGitHubFile(String repoSlug, String filename, String commit) {
        String result = null
        withCredentials(string([credentialsId: 'credentials', variable: 'token'])) {
            String jenkinsfileUrl = "https://gitlab_url.net/${repoSlug}/-/blob/${commit}/${filename}"
            try {
                result = httpRequest(url: jenkinsfileUrl).content
            }
            catch (Exception e) {
                echo "Failed to fetch '${filename}'"
            }
        }
        return result
    }
    ```
    The error intellij is raising is:
    ```
    No signature of method: TestPrueba.string() is applicable for argument types: (LinkedHashMap) values: [[credentialsId: 'credentials', variable: 'token']]
Possible solutions: toString(), toString(), stream(), print(java.io.PrintWriter), print(java.lang.Object), find()
groovy.lang.MissingMethodException: No signature of method: TestPrueba.string() is applicable for argument types: (LinkedHashMap) values: [[credentialsId: 'credentials', variable: 'token']]
Possible solutions: toString(), toString(), stream(), print(java.io.PrintWriter), print(java.lang.Object), find()
```

im not very versed on groovy so any hint on how to fix it would be appreciatted :pray: if you need the full stack trace let me know.
Thank you in advance

**Comment by nre-ableton** [comment]
Do you have the [`credentials-binding` plugin](https://plugins.jenkins.io/credentials-binding/) installed on your Jenkins?

**Comment by Lemming3842** [comment]
mmm that might be the issue, i'm gonna try on a jenkins with the plugin and let you know if it solved the problem!

**Comment by Lemming3842** [comment]
Hello! the with credentials indeed was because of my local jenkins plugin. Sorry for the late delay but life was complicated T_T . Thank you very much for all the help given you can close this issue now :)

**Comment by nre-ableton** [comment]
Glad that you got it working!
