### ISSUE TITLE
Mocking different return values for a method the second time it is called

### ISSUE THREAD

**Issue by ldonnellanIDBS** [jenkinsci/JenkinsPipelineUnit#607]
### Describe your use-case which is not covered by existing documentation.

I have a pipeline that contains a while loop. The while loop reads messages from a queue until either it finds one it can do something with or runs out of messages to read. I have written a happy path test for this pipeline by mocking the message. 

I was trying to write a test to assert the behaviour when the first message cannot be serviced for some reason.

In my head, the test is something like:
- First mock trigger returns a message that cannot be serviced for some reason (pipeline continues the loop)
- Second mock trigger returns a message that can be serviced.
- Assert that two messages were read and no more

Note that since the method call being mocked is making a call to a queue, the method parameters are identical.

I looked through the docs, but couldn't see an obvious example of how to change the mock behaviour on subsequent calls when the parameters are the same both times - is this possible? Any tips would be appreciated - thanks!

**Comment by nre-ableton** [comment]
Most likely, I think the solution for this would be overridding one of the default mocks and providing your own class to provide this functionality. I'd imagine the easiest way to implement this would to simply store the number of times the mock was called in a static integer and return different results based on this value.

BTW what is the exact pipeline step that you are trying to mock here?

**Comment by ldonnellanIDBS** [comment]
Thanks very much for the swift response! For some reason it didn't occur to me that I could simply create a static variable and track it in the mock. Makes total sense and solved the problem 👍

**Comment by nre-ableton** [comment]
@ldonnellanIDBS glad to hear that you found a solution! :+1:
