### ISSUE TITLE
How to test the when step in a stage

### ISSUE THREAD

**Issue by jdoshi1** [jenkinsci/JenkinsPipelineUnit#63]
I want to test that the stage with my shared lib executes based on the when environment expression being true.

For ex:
```groovy
pipeline {
    agent none
    stages {
        stage("Shared Lib 1") {
            agent any
            when {
                environment name:'SHARED_LIB_1', value: 'true'
            }
            steps {
                sharedLib1()
            }
        }
    }
}
```

This is what I was using:
```groovy
helper.registerAllowedMethod('environment', [Map.class], {it -> (it.value == binding.getProperty('env')["SHARED_LIB_1"]) })
helper.registerAllowedMethod('when', [Closure.class], {c -> c.call()})
```
It always executes the stage for any value of SHARED_LIB_1 set in the environment.

How to go about testing the `when` condition in stage with environment expression? Thanks.

**Comment by stchar** [comment]
I cannot find implementation of `when` and `stage`. 
If you expects that if `when` returns false then entire `stage` is skipped so the first came in my mind is to use `try-catch`
```
helper.registerAllowedMethod('environment', [Map.class], {it -> (it.value == binding.getProperty('env')[it.name]) })
```
Throw exception in when
```
helper.registerAllowedMethod('when', [Closure.class], {c -> 
    if(!c.call()){
         throw new Exception("conditional check failed")
    } 
})
```
Override `stage`
```
helper.registerAllowedMethod('stage', [String.class, Closure.class], {s, c -> 
     try {
          c.call()
     } catch(Exception e) {
          if(!e.message.contains("conditional check failed")) {
             throw e
         }
     }  
})
```

**Comment by stchar** [comment]
i'm closing the issue. If you still need help please refer to the gitter channel. https://gitter.im/JenkinsPipelineUnit/Lobby
