### ISSUE TITLE
Specify a way to add helper.registerAllowedMethod("readYaml") as per the stage

### ISSUE THREAD

**Issue by gaiksaya** [jenkinsci/JenkinsPipelineUnit#647]
Hi,

We have a pipeline with parallel stages here: https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/publish-min-snapshots.jenkinsfile

The shared library used in the pipeline loads a yaml file but it differs in each stage. Is there a way we can mock readYaml as per the stage? Maybe based on stage name?

Thanks!
```[tasklist]
### Tasks
```

**Comment by nre-ableton** [comment]
It's gonna be hacky, but I think you'll need to register closures for both the `stage` and `readYaml` methods. In other words, something along these lines:

```groovy
@Test
void testWhatever() {
  String currentStage = null
  helper.registerAllowedMethod('stage', [String]) { name, body ->
    currentStage = name
    body()
  }
  helper.registerAllowedMethod('readYaml', [Map]) { args ->
    switch (currentStage) {
      case 'stage1':
        // stuff
        return [foo: 'bar']
      // etc
      default:
        return [:]
    }
  }
}
```

**Comment by gaiksaya** [comment]
Hi @nre-ableton,

Thanks for recommending the solution. I did try that. However, the stage name is always null. So I added print statements for debugging. Looks like `helper.registerAllowedMethod('stage'` is never called. Hence the `currentStage` is always `null`

**Comment by nre-ableton** [comment]
Sorry, the mock needs to be declared with `[String, Closure]` (I wrote my above comment on the train from memory 😅). Like so: https://github.com/jenkinsci/JenkinsPipelineUnit/blob/3552fe062d2b339ddee963c1db9093ef30fef6c4/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L257

**Comment by gaiksaya** [comment]
This was a huge help. Able to replicate mock readYaml as per stage now.

Thank you so much @nre-ableton :)
