### ISSUE TITLE
Help needed - testing with an implicitly loaded global library

### ISSUE THREAD

**Issue by choppedpork** [jenkinsci/JenkinsPipelineUnit#68]
Hello,

I'm trying to add the simplest of tests to my existing (non-declarative) pipelines. As someone who is not a Java developer this is all rather daunting but I seem to, slowly, be getting somewhere! I have unfortunately ran into what seems like a road block. My company currently has a single shared library which is loaded implicitly by Jenkins. We use the library as follows:
```
def slack = new com.blah.jenkins.util.slack()

(...)

node {
  slack.notification(slackChannel, "<${env.BUILD_URL}|${env.BUILD_NUMBER}> failed :disappointed:")
}
```

I believe I've got my helper configured correctly (which is set to implicitly load the shared library from a remote git repo) however am running into a problem during the compile stage, not during the test stage. All the `new` calls to the shared library fail (as it's not been loaded - this is the pre-test compilation stage):

```
[ERROR] 	def slack = new com.blah.jenkins.util.slack()
[ERROR] 	                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Groovy:unable to resolve class com.blah.jenkins.util.slack
```

I've tried adding an explicit `@Library` annotation but that resulted in a compile-time error as well:

```
[ERROR] 	@Library('common')
[ERROR] 	 ^^^^^^^
[ERROR] Groovy:unable to resolve class Library ,  unable to find class for annotation
```

I've had a look at a few example repos but these never seem to include any extra compile-time dependencies to make the `@Library` annotation work (ideally, if possible, I'd like to keep the existing code as-is ie. with implicit library loading and without annotations - is there a way to do this?).

Thanks in advance!

**Comment by choppedpork** [comment]
Not sure what I did wrong initially - closing.

**Comment by poliveira-fuze** [comment]
@choppedpork I'm having this issue how did you configured the helper?
And were you able to fix this issue? I'm asking since the ticket was closed by you any detailed explanation.
