### ISSUE TITLE
Version 1.23 is not available in dedicated maven repo

### ISSUE THREAD

**Issue by jgraglia** [jenkinsci/JenkinsPipelineUnit#682]
### Jenkins and plugins versions report

The `1.23` release  does not seems to be available in the dedicated repo.
The [maven doc](https://github.com/jenkinsci/JenkinsPipelineUnit?tab=readme-ov-file#maven) claims that the artifacts are available on https://repo.jenkins-ci.org/releases/ but
https://repo.jenkins-ci.org/releases/com/lesfurets/jenkins-pipeline-unit/ last available version is 1.22

The `1.23` version has been created a week ago. (sept, 27)

mvnrepository.com also does not find the release

https://mvnrepository.com/artifact/com.lesfurets/jenkins-pipeline-unit?repo=jenkins-releases

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux for both controller & agents

### Reproduction steps

Go to https://repo.jenkins-ci.org/releases/com/lesfurets/jenkins-pipeline-unit/
1.23 version is missing

### Expected Results

The 1.23 version should be available in the jenkins repo.

### Actual Results

The last available version is 1.22

**Comment by nre-ableton** [comment]
Sorry, I forgot to run `./gradlew artifactoryPublish`. I've run it now and the artifacts are on https://repo.jenkins-ci.org/releases/com/lesfurets/jenkins-pipeline-unit/1.23/.

**Comment by jgraglia** [comment]
Great , thank you for this quick answer !!

btw a 1.24 version is now also available , but not available in github .
![Image](https://github.com/user-attachments/assets/086deb81-efb4-4ba4-af1a-4b97e6178ac5)
https://repo.jenkins-ci.org/releases/com/lesfurets/jenkins-pipeline-unit/

**Comment by nre-ableton** [comment]
Yeah, I know. I ran `gradlew artifactoryPublish` from `master`, which did that by accident. We'll probably have to skip that version and go to 1.25, because I don't have overwrite permissions in Artifactory.

The binary is the same as 1.24, though.
