### ISSUE TITLE
Question: Testing Shared Library definition using JenkinsPipelineUnit

### ISSUE THREAD

**Issue by mkobit** [jenkinsci/JenkinsPipelineUnit#70]
I (finally) released the first version of https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin , which is a Gradle plugin intending to aid in the authoring of shared libraries. I'm sure an additional plugin could be added to support consumers of `JenkinsPipelineUnit` for build pipeline authors that also want to test their pipeline.

I wrote up an example library at https://github.com/mkobit/jenkins-pipeline-shared-library-example, but was struggling in writing a unit test against the local shared library functionality (at https://github.com/mkobit/jenkins-pipeline-shared-library-example/blob/master/test/unit/groovy/com/mkobit/libraryexample/JPUExampleSpec.groovy right now).

Any suggestions or example  to look at for using this as a test harness for Shared Library definition?

**Comment by jimcroft** [comment]
Hi @mkobit 

I've put a basic skeleton example of what I'm doing here: https://github.com/jimcroft/jenkinslib-example. Hope it helps. If that example does help you load your Jenkins library from a local location (rather than an scm source) could you add a comment to https://github.com/jenkinsci/JenkinsPipelineUnit/pull/75?

Thanks

Jim

**Comment by balux** [comment]
Waiting for "local-location" solution too! Meanwhile you can use a copy task in your `build.gradle`
```groovy
task initLibraries(type: Copy){
    from('./') {
        include 'src/**/*'
        include 'vars/**/*'
    }
    into 'build/classes/groovy/test/nextlayerci-example@master'
}

test.dependsOn initLibraries
```
https://github.com/nextlayer-ops/jenkins-pipeline-shared-library-example/blob/master/build.gradle#L12-L20
and 
https://github.com/nextlayer-ops/jenkins-pipeline-shared-library-example/blob/master/test/groovy/SayHelloTest.groovy#L18-L30

Btw. If you want to use maven you can use the same trick:
https://github.com/nextlayer-ops/jenkins-pipeline-shared-library-example-maven/blob/master/pom.xml#L54-L80

**Comment by mkobit** [comment]
https://github.com/jenkinsci/JenkinsPipelineUnit/pull/75 and https://github.com/jenkinsci/JenkinsPipelineUnit/pull/64 are both related to this, would be great to see one of those move forward

**Comment by balux** [comment]
Meanwhile I've found a better solution. Thanks to the SAP guys ;)

https://github.com/SAP/jenkins-library/blob/master/test/groovy/PiperTestBase.groovy#L49-L59

**Comment by stchar** [comment]
Closing in a favor of #31
