### ISSUE TITLE
Unkown interceptors for nested library calls when using explicit script invocation

### ISSUE THREAD

**Issue by jacobfederer** [jenkinsci/JenkinsPipelineUnit#71]
I'm trying to invoke a script method explicitly via `Script.invokeMethod()` in order to avoid the usage of a declarative pipeline which would be a lot of overhead for my use case. The script contains multiple library steps which have been registered through an implicit shared library and `PipelineTestHelper.registerSharedLibrary() `. My issue is that nested library calls don't recognize the registered method interceptors from `PipelineTestHelper.registerAllowedMethod` with the exception: 

```
groovy.lang.MissingMethodException: No signature of method: handleStepErrors.echo() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [--- END LIBRARY STEP: publishTestResults.groovy ---]
Possible solutions: each(groovy.lang.Closure), wait(), run(), run(), find(), any()
```

**Comment by fordperfect78** [comment]
👍

**Comment by jacobfederer** [comment]
Resolved, caused by a wrong compiler configuration which didn't respect the `LibraryAnnotationTransformer`.

**Comment by ozangunalp** [comment]
Hey @jacobfederer sorry for responding this late. 

When I saw the issue I was wondering if the LibraryAnnotationTransformer did not work for some reason. Could you give more detail on the compiler configuration which disabled the transformer?

And there is no need for #72 ?

**Comment by jacobfederer** [comment]
I used the built-in Intellij execution which was configured with a Maven pom. A build in Intellij resulted in not triggering the transformer but also Maven used the same cached non working version. 

Yes, the PR is irrelevant.
