### ISSUE TITLE
Provide a way to cache the PipelineTestHelper and dependent libraries

### ISSUE THREAD

**Issue by jacobfederer** [jenkinsci/JenkinsPipelineUnit#73]
The `PipelineTestHelper ` does a lot of heavy lifting e.g. loading a library from various sources. Since the library content doesn't change during the test execution it would be good to provide a way to cache this helper and it's dependent libraries to speed up the test execution and reducing the I/O effort.

**Comment by ozangunalp** [comment]
You can call the `BasePipelineTest#setUp` method in the per class initializer of your test runner.
For example if you are using JUnit you can call the setUp method in your `@BeforeClass` method as in 

```java
class PipelineJobTest extends BasePipelineTest {
    
    @BeforeClass
    void initTests() throws Exception {
        super.setUp();
    }
```

**Comment by jacobfederer** [comment]
Unfortunately this is not possible since `@BeforeClass` requires the method to be static. This is caused by the fact that every `@Test` method will be executed in a separate instance of the referenced test class.

**Comment by ssbarnea** [comment]
We have our shared library inside a git repository and we are using the `.retriever(GitSource.gitSource(...))` approach to load the shared library... and we have >1300 jobs to tests. If that's true it means that we perform a serious DDOS against git server.

Any workarounds?

**Comment by stchar** [comment]
I assume this one could be closed.
