### ISSUE TITLE
Issue with mocking variables used by shared library methods

### ISSUE THREAD

**Issue by choppedpork** [jenkinsci/JenkinsPipelineUnit#88]
Hello,

I'm testing a pipeline which uses a library method which needs access to some of Jenkins' built in variables. Whenever I try to create a binding.setVariable for those they work correctly in the pipeline itself but not in the method. Is there any way to achieve this? Alternatively - how can I mock this method (which would be even better - I've naively tried the following which obviously didn't work)?
```
helper.registerAllowedMethod("build.cleanDockerContainers", [String.class, String.class], null)
```

Here's the pipeline:
```
def build = new com.test.jenkins.build.build()

try {
  node('AT-executor') {

    build.cleanDockerContainers('none', 'yes')
```

The cleanDockerContainers method tries to access the `WORKSPACE` environment variable but fails with
```
groovy.lang.MissingPropertyException: No such property: WORKSPACE for class: com.test.jenkins.build.build
```

The tests have been set up like this:
```
    @Override
    @Before
    void setUp() {

        def library = library()
            .name('commons')
            .retriever(gitSource("blah"))
            .targetPath(temp.path)
            .defaultVersion("master")
            .allowOverride(true)
            .implicit(true)
            .build()

        helper.registerSharedLibrary(library)

        helper.registerAllowedMethod("wrap", [java.util.LinkedHashMap, groovy.lang.Closure], null)
        binding.setVariable('environment', 'test1')
        binding.setVariable('WORKSPACE', '/tmp')
        binding.setVariable('env', [
          BUILD_NUMBER : '1',
          BUILD_URL: 'example.com'
        ])
        super.setUp()

    }
```

**Comment by stchar** [comment]
I think this is classical issue)) 

try to pass pipeline instance reference to the library
```groovy
// pipeline
def build = new com.test.jenkins.build.build()
build.laMethod()
```
```groovy
// library class
class build {
  // this field contain reference to pipeline object
  def script;
  // construnctor
  build(script) { 
    this.script = script
  }
  // To access pipeline context refer to the script field 
  def laMethod() {
    script.echo "BUILD_URL = $script.env.BUILD_URL"
    script.echo "WORKSPACE = $script.WORKSPACE"
  }
} 
```

**Comment by choppedpork** [comment]
Thanks @stchar - this will require us to rewrite our existing library but I've added some new functionality in this way and it's working great! Your solutions is a nice 2-in-1 for me because this also allows me to test the library methods in isolation which is something I wanted to do for a long time now.

**Comment by sadaram144** [comment]
@choppedpork Can you share us how you have added that "New Functionality" to work this way. We are also Currently blocked to refactor and work on this, Please share your Logic, we will implement and avoid rewriting the Pipeline code, Our pipeline code is Huge Ocean, Cant refactor. Your Inputs will be really appreciated. @choppedpork waiting for your response.
