### ISSUE TITLE
Why isn't setUp() in BasePipelineTest annotated with @Before?

### ISSUE THREAD

**Issue by nre-ableton** [jenkinsci/JenkinsPipelineUnit#90]
I'm sure there's a good reason for this, but can someone explain to me why `BasePipelineTest.setUp()` lacks the `@Before` annotation? I find it a bit weird that I need to add this empty override to my unit test classes (in some cases) just to get everything working:

```
@Override
@Before
void setUp() throws Exception {
    super.setUp()
}
```

Looking at the main build.gradle file, I can see that JUnit is added as a `testCompile` dependency and not a `compile` dependency, so I'm assuming this has something to do with it. I guess I should also ask why this is the case. Is the idea to support other testing frameworks?

Thanks!

**Comment by stchar** [comment]
I believe one does not can simply answered this question ))) IMHO this is a miss.

**Comment by stchar** [comment]
Maybe @ozangunalp can explain it.

**Comment by stchar** [comment]
I suppose this one could be closed
