### ISSUE TITLE
Mocking findFiles step

### ISSUE THREAD

**Issue by zrks** [jenkinsci/JenkinsPipelineUnit#91]
Currently I'm trying to register findFiles step.
My set up is as follows:
```sh
src/
    test/
        groovy/
            TestJavaLib.groovy
vars/
    javaLib.groovy
javaApp.jenkinsfile
```

Inside TestJavaApp.groovy I have:
```groovy
...
import com.lesfurets.jenkins.unit.RegressionTest
import com.lesfurets.jenkins.unit.BasePipelineTest

class TestJavaLibraryPipeline extends BasePipelineTest implements RegressionTest {
    // Some overridden setUp() which loads shared libs
    // and registers methods referenced in javaApp.jenkinsfile

    void registerPipelineMethods() {
...
        def fileList = [new File("testFile1"), new File("testFile2")]
        helper.registerAllowedMethod('findFiles', { f -> return fileList })
    }
}
```
and my javaApp.jenkinsfile contains this currently failing part:
```groovy
...
    def pomFiles = findFiles glob: "target/publish/**/${JOB_BASE_NAME}*.pom"
    if (pomFiles.length < 1) { // Fails with java.lang.NullPointerException: Cannot get property 'length' on null object
        error("no pom file found")
    }
...
```

I have tried multiple closures returning various objects, but everytime I get NPE.
Question is - how to correctly register "findFiles" method?

N.B. That I'm very new to mocking and closures in groovy.

**Comment by brianeray** [comment]
I think it's because you're registering a *no* argument method signature (ie `findFiles()`) but your test is invoking the one argument variant, passing a list of map entries that is coerced into a `Map`. Your method interceptor is not a match in this case.

Try this.

```
helper.registerAllowedMethod('findFiles', [Map], { _ -> return fileList })
```
In that closure I'm ignoring the parameter passed in because you've hardcoded the return value, hence the "I don't care" underscore.

**Comment by brianeray** [comment]
Here is a similar example in [`BasePipelineTest` itself](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L76) with a one-arg method signare and a hardcoded closure. I suspect like it you could simplify my first suggestion and forego the closure param declarations entirely. Plus be Groovy and omit `return`, e.g.

```
helper.registerAllowedMethod('findFiles', [Map], { fileList })
```

**Comment by zrks** [comment]
I had to mention that I tried various method signatures. Even if I try your suggestion I still get NPE when that conditional check is executed. So my assumption is that findFiles isn't intercepted and value isn't returned to pomFiles variable hence the NPE.

As I'm new to groovy I'm not even sure on how to debug this. Suggestions?

**Comment by brianeray** [comment]
@zrks, I will try to replicate what you are experiencing. Hopefully I will have some time on Friday.

**Comment by stchar** [comment]
@zrks 
`Map.class` be careful.
helper.registerAllowedMethod('findFiles', [Map.class], { _ -> return ['foo','bar'] })

If it does't work, please share the stack trace.

**Comment by zrks** [comment]
@stchar 
I managed to solve this by registering method like this:
```groovy
helper.registerAllowedMethod('findFiles', [Map.class], { [length: findFilesLength ?: 1] })
```

By using property `findFilesLength` I am able to play out different scenarios in my tests as I have conditional check in my pipeline file.

Thanks!

Closing this one.
