### ISSUE TITLE
Testing error handling in Jenkinsfile

### ISSUE THREAD

**Issue by julioarmandof** [jenkinsci/JenkinsPipelineUnit#94]
Hi everyone, 

Quick question; How would be the best way to test error handling in a Jenkinsfile?, I mean, let's say that the shell command returned an exit code `2` or something different than `0` which would cause the pipeline to fail and not process the remaining stages / steps, is there any standard / best practice way to achieve this?

**Comment by stchar** [comment]
There some methods I use. Let's say you have a pipeline to build in your project.
```groovy
// example.groovy
node() {
  git('some_repo_url')
  sh "make"
}
```
you can mock `sh` step whether to throw an Exception or whether to just update build status to failure. 


To verify your pipeline is failing you can:
* Check build status with `BasePipelineTest.assertJobStatusFailure()`
* Check if exception occurs with
```java
@org.junit.Rule org.junit.rules.ExpectedException
```

```groovy
import org.junit.Rule
import org.junit.rules.ExpectedException
class TestCase extends BasePipelineTest {
  // testcase
  @Rule
  public ExpectedException thrown = ExpectedException.none();

  @Test
  void check_build_status() throws Exception {
      helper.registerAllowedMethod("sh", [String.class], {cmd-> 
        if (cmd.contains("make")) {
          binding.getVariable('currentBuild').result = 'FAILURE'
        }
     })
    def script = runScript("example.groovy")
    assertJobStatusFailure()
  }

 @Test
  void check_exception() throws Exception {
      helper.registerAllowedMethod("sh", [String.class], {cmd-> 
        if (cmd.contains("make")) {
          throw new Exception("error message")
        }
     })
    def script = runScript("example.groovy")
    thrown.expect(Exception)
    thrown.expectMessage("error message");
  }
}
```

**Comment by julioarmandof** [comment]
Thanks, @stchar!
