### ISSUE TITLE
Question: How to use Spock instead JUnit

### ISSUE THREAD

**Issue by goostleek** [jenkinsci/JenkinsPipelineUnit#96]
I would like to use the library with Spock instead JUnit. Is this possible?

**Comment by stchar** [comment]
Hi @goostleek, please take a look at https://github.com/macg33zr/pipelineUnit

As demo projects I can recommend:
https://github.com/mkobit/jenkins-pipeline-shared-library-example
https://github.com/SpencerMalone/JenkinsPipelineIntegration

**Comment by stchar** [comment]
Add to docs

**Comment by stchar** [comment]
Closing in favor of #31
