### ISSUE TITLE
Configuration Steps don't Override default values helper.init() 

### ISSUE THREAD

**Issue by Moser-ss** [jenkinsci/JenkinsPipelineUnit#97]
Hi everyone,

Looks the steps we have in readme.md file don't work, when I try to override the default values  nothing it is change
My code 
```groovy
 @Override
    @Before
    public void setUp() throws Exception {
        helper.baseScriptRoot = 'foo-bar'
        helper.scriptRoots = 'src/main/groovy/com/mycompany/jenkins/'
        helper.scriptExtension = 'pipeline'
        super.setUp()
 }
```
When I debug the super.setUp() method it returns a helper instance with the default values

**Comment by stchar** [comment]
You need to call `super.setUp()` before to alter `helper` instance
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/main/groovy/com/lesfurets/jenkins/unit/BasePipelineTest.groovy#L38

**Comment by stchar** [comment]
This is duplication of #80 
PR https://github.com/jenkinsci/JenkinsPipelineUnit/pull/81
