### ISSUE TITLE
How to inspect the pipeline when there is a failure

### ISSUE THREAD

**Issue by eciramella** [jenkinsci/JenkinsPipelineUnit#99]
Hi all - 

I'm using version 1.0 of this library to test a pipeline file with a shared library.

Is there any way to see what step exactly (any hopefully why) a particular test failed?

I'm only seeing the call stack like this:
`FAILURE
   Jenkinsfile.run()
   Jenkinsfile.execute()
      Jenkinsfile.node(groovy.lang.Closure)
         Jenkinsfile.echo(Oh snap)
         Jenkinsfile.shutdownContainers(projectname)
            shutdownContainers.sh(
     //docker shutdown steps here
  )`
That isn't very helpful as I'm just seeing my catch statement.

**Comment by stchar** [comment]
@eciramella 
Please take a look at https://github.com/jenkinsci/JenkinsPipelineUnit/issues/94

**Comment by stchar** [comment]
Closing in favour of #94
